import { defineConfig } from "vite-plus";

export default defineConfig({
  pack: {
    tsconfig: "tsconfig.build.json",
    outExtensions: () => ({ js: ".js", dts: ".d.ts" }),
    report: false,
    entry: [
      "src/core/extensions/adapters/pgrouting.ts",
      "src/tooling/extensions/operations/pgrouting.ts",
      "src/core/extensions/adapters/pg-hashids.ts",
      "src/core/extensions/adapters/pgtap.ts",
      "src/tooling/extensions/operations/pgtap.ts",
      "src/index.ts",
      "src/tooling/extensions/operations/postgis_raster.ts",
      "src/core/extensions/adapters/postgis-raster.ts",
      "src/tooling/extensions/operations/postgis-tiger-geocoder.ts",
      "src/core/extensions/adapters/postgis-tiger-geocoder.ts",
      "src/tooling/extensions/operations/lakebase_tokenizer.ts",
      "src/core/extensions/adapters/lakebase_tokenizer.ts",
      "src/core/extensions/adapters/lakebase-text.ts",
      "src/core/extensions/adapters/address-standardizer-data-us.ts",
      "src/core/extensions/adapters/timescaledb.ts",
      "src/tooling/extensions/operations/timescaledb.ts",
      "src/cli.ts",
      "src/core/contract/index.ts",
      "src/core/server/index.ts",
      "src/core/client/index.ts",
      "src/core/react/index.ts",
      "src/core/react/neon.ts",
      "src/core/better-auth/index.ts",
      "src/core/next/server.ts",
      "src/core/start/server.ts",
      "src/core/adapters/neon/index.ts",
      "src/core/extensions/adapters/pg-trgm.ts",
      "src/core/extensions/adapters/pgcrypto.ts",
      "src/core/extensions/adapters/fuzzystrmatch.ts",
      "src/core/extensions/adapters/ltree.ts",
      "src/core/extensions/adapters/pg-tiktoken.ts",
      "src/core/extensions/adapters/pg-jsonschema.ts",
      "src/core/extensions/adapters/uuid-ossp.ts",
      "src/core/extensions/adapters/citext.ts",
      "src/core/extensions/adapters/pg-uuidv7.ts",
      "src/core/extensions/adapters/unaccent.ts",
      "src/core/extensions/adapters/hstore.ts",
      "src/tooling/extensions/operations/neon.ts",
      "src/core/extensions/adapters/neon.ts",
      "src/core/extensions/adapters/pg_partman.ts",
      "src/core/extensions/adapters/pg_cron.ts",
      "src/tooling/extensions/operations/pg_cron.ts",
      "src/tooling/extensions/operations/pg_partman.ts",
      "src/core/extensions/adapters/neon_utils.ts",
      "src/tooling/extensions/operations/hypopg.ts",
      "src/core/extensions/adapters/hypopg.ts",
      "src/core/extensions/adapters/btree_gist.ts",
      "src/core/extensions/adapters/vector.ts",
      "src/core/extensions/adapters/lakebase-vector.ts",
      "src/core/extensions/adapters/insert-username.ts",
      "src/core/extensions/adapters/refint.ts",
      "src/core/extensions/adapters/tcn.ts",
      "src/core/extensions/adapters/lo.ts",
      "src/core/extensions/adapters/pg_prewarm.ts",
      "src/core/extensions/adapters/anon.ts",
      "src/tooling/extensions/operations/anon.ts",
      "src/core/extensions/adapters/pg_repack.ts",
      "src/core/extensions/adapters/plpgsql_check.ts",
      "src/core/extensions/adapters/postgres_fdw.ts",
      "src/tooling/extensions/operations/postgres_fdw.ts",
      "src/core/extensions/adapters/pg_stat_statements.ts",
      "src/core/extensions/adapters/pgjwt.ts",
      "src/core/extensions/adapters/pg_session_jwt.ts",
      "src/tooling/extensions/operations/pg_session_jwt.ts",
      "src/tooling/extensions/operations/lo.ts",
      "src/tooling/extensions/operations/pg_prewarm.ts",
      "src/tooling/extensions/operations/pg_repack.ts",
      "src/tooling/extensions/operations/plpgsql_check.ts",
      "src/tooling/extensions/operations/pg_stat_statements.ts",
      "src/core/extensions/adapters/pg_hint_plan.ts",
      "src/tooling/extensions/operations/pg_hint_plan.ts",
      "src/tooling/extensions/tcn.ts",
      "src/core/extensions/adapters/postgis.ts",
      "src/tooling/extensions/operations/postgis.ts",
      "src/core/extensions/adapters/postgis-sfcgal.ts",
      "src/core/extensions/adapters/postgis-topology.ts",
      "src/tooling/extensions/operations/postgis-topology.ts",
      "src/core/extensions/adapters/rdkit.ts",
      "src/tooling/extensions/operations/rdkit.ts",
      "src/core/extensions/adapters/address-standardizer.ts",
      "src/tooling/extensions/operations/address-standardizer.ts",
      "src/core/extensions/adapters/cube.ts",
      "src/core/extensions/adapters/dblink.ts",
      "src/tooling/extensions/operations/dblink.ts",
      "src/core/extensions/adapters/xml2.ts",
      "src/core/extensions/adapters/tablefunc.ts",
      "src/core/extensions/adapters/pg_graphql.ts",
      "src/core/extensions/adapters/ip4r.ts",
      "src/core/extensions/adapters/h3.ts",
      "src/core/extensions/adapters/btree_gin.ts",
      "src/core/extensions/adapters/bloom.ts",
      "src/core/extensions/adapters/earthdistance.ts",
      "src/core/extensions/adapters/h3-postgis.ts",
      "src/core/extensions/adapters/seg.ts",
      "src/core/extensions/adapters/intagg.ts",
      "src/core/extensions/adapters/intarray.ts",
      "src/core/extensions/adapters/hll.ts",
      "src/core/extensions/adapters/isn.ts",
      "src/core/extensions/adapters/roaringbitmap.ts",
      "src/tooling/extensions/operations/roaringbitmap.ts",
      "src/tooling/extensions/operations/isn.ts",
      "src/core/extensions/adapters/semver.ts",
      "src/tooling/extensions/operations/semver.ts",
      "src/core/extensions/adapters/pgx-ulid.ts",
      "src/tooling/extensions/hll.ts",
      "src/core/extensions/adapters/prefix.ts",
      "src/core/extensions/adapters/dict_int.ts",
      "src/tooling/extensions/operations/dict_int.ts",
      "src/core/extensions/adapters/autoinc.ts",
      "src/core/extensions/adapters/moddatetime.ts",
      "src/core/extensions/adapters/pgstattuple.ts",
      "src/core/extensions/adapters/pgrowlocks.ts",
      "src/core/extensions/adapters/tsm-system-rows.ts",
      "src/core/extensions/adapters/tsm-system-time.ts",
      "src/core/extensions/native-timestamp-codecs.ts",
      "src/tooling/extensions/pg-trgm.ts",
      "src/tooling/extensions/unaccent.ts",
      "src/tooling/index.ts",
      "src/tooling/neon/credential-worker.ts",
    ],
    root: "src",
    unbundle: false,
    format: "esm",
    platform: "node",
    target: "es2023",
    dts: true,
    sourcemap: true,
    deps: {
      neverBundle: true,
      alwaysBundle: [/^(drizzle-kit|zod|@neon\/config(?:-runtime)?)(\/|$)/],
      onlyBundle: [/^(drizzle-kit|zod|@neon\/config(?:-runtime)?)(\/|$)/],
    },
  },
});
