import { expect } from "vite-plus/test";
import { extensionProofUnitTest } from "../../e2e/fixtures/extension-proof-unit";
import { ip4rUnitProofCase, ip4rMembershipUnitProofCase } from "../../e2e/fixtures/ip4r-proof-cases";
import { createIp4r_2_4, ip4rValue } from "../../../apps/loom/src/core/extensions/adapters/ip4r";
import manifest from "../../../apps/loom/src/tooling/extensions/manifests/ip4r.json";
import { ip4rAnnotations } from "../../../apps/loom/src/tooling/extensions/annotations/ip4r";
import { extensionSqlDialect, extensionExpressionContract } from "../../../apps/loom/src/core/extensions/sql";
import { nodePgCodecs } from "drizzle-orm/node-postgres";
const descriptor = { name: "ip4r", version: "2.4", schema: 'Ip4r"日本', apiSupport: { status: "verified", digest: "477396650c5a07dc747e68b59df1af6c2bd6a8de1f2b7aff640fd717e2eebca9" } } as const;
extensionProofUnitTest(ip4rUnitProofCase, () => {
  const api = createIp4r_2_4(descriptor);
  expect(api.ip4.codec.encode(ip4rValue("ip4", "192.0.2.1"))).toBe("192.0.2.1");
  expect(api.ip4.codec.decode("192.0.2.1")).toEqual(ip4rValue("ip4", "192.0.2.1"));
  expect(api.ip4r.codec.decode("192.0.2.0/24")).toEqual(ip4rValue("ip4r", "192.0.2.0/24"));
  expect(api.ip4r.codec.encode(ip4rValue("ip4r", "192.0.2.1-192.0.2.10"))).toBe("192.0.2.1-192.0.2.10");
  expect(api.ip6.codec.decode("2001:db8::1")).toEqual(ip4rValue("ip6", "2001:db8::1"));
  expect(api.ip6r.codec.decode("2001:db8::/32")).toEqual(ip4rValue("ip6r", "2001:db8::/32"));
  expect(api.ipaddress.codec.decode("192.0.2.1")).toEqual(ip4rValue("ipaddress", "192.0.2.1"));
  expect(api.iprange.codec.decode("-")).toEqual(ip4rValue("iprange", "-"));
  expect(() => api.ip4.codec.decode("3232235777")).toThrow();
  expect(() => api.ip4.codec.decode("192.0.2.01")).toThrow();
  // @ts-expect-error incompatible kind
  expect(() => api.ip4.codec.encode(ip4rValue("ip6", "2001:db8::1"))).toThrow();
  for (const malformed of ["", "1.2.3", "192.0.2.256", "not-an-ip", "192.0.2.1/33", "2001::db8::1"]) expect(() => api.ip4.codec.decode(malformed)).toThrow();
  const array = { dimensions: [{ lowerBound: -2, length: 2 }, { lowerBound: 4, length: 2 }], values: [[ip4rValue("ip4", "192.0.2.1"), null], [ip4rValue("ip4", "192.0.2.2"), ip4rValue("ip4", "192.0.2.3")]] };
  expect(api.ip4.arrayCodec.decode(api.ip4.arrayCodec.encode(array))).toEqual(array);
  expect(api.ip4.arrayCodec.decode("{}")).toEqual({ dimensions: [], values: [] });
  expect(() => api.ip4.arrayCodec.encode({ dimensions: [{ lowerBound: 2147483647, length: 1 }], values: [ip4rValue("ip4", "192.0.2.1")] })).toThrow();
});
extensionProofUnitTest(ip4rMembershipUnitProofCase, () => {
  const api = createIp4r_2_4(descriptor);
  expect(ip4rAnnotations.map((row) => row.id).sort()).toEqual(manifest.contract.members.map((row) => row.id).sort());
  expect(new Set(ip4rAnnotations.map((row) => row.id)).size).toBe(591);
  const callable = manifest.contract.members.filter((m) => m.kind === "operator" || (m.kind === "routine" && !m.arguments?.some((a) => ["internal", "cstring"].includes(a.type.name)) && m.returns?.name !== "cstring"));
  expect(Object.keys(api.sql.overloads).sort()).toEqual(callable.map((row) => row.id).sort());
  expect(callable.length).toBe(341);
  expect(Object.keys(api.sql.casts).sort()).toEqual(manifest.contract.members.filter((row) => row.kind === "cast").map((row) => row.id).sort());
  const expression = api.ip4.equal(ip4rValue("ip4", "192.0.2.1"), ip4rValue("ip4", "192.0.2.2"));
  expect(extensionExpressionContract(expression)?.member).toBe("operator:$extension:ip4r.=($extension:ip4r.ip4,$extension:ip4r.ip4)");
  const query = extensionSqlDialect(nodePgCodecs).sqlToQuery(expression);
  expect(query.sql).toContain('operator("Ip4r""日本".=)');
  expect(query.params).toEqual(["192.0.2.1", "192.0.2.2"]);
  expect(extensionExpressionContract(api.sql.functions.family.ip4(ip4rValue("ip4", "192.0.2.1")))?.codec).toContain("nullable");
  expect(api.ip4.field().metadata.extension).toMatchObject({ type: "ip4", schema: descriptor.schema, codec: "ip4r:ip4:typed-text:1" });
  expect(api.ip4.arrayField().metadata.extension).toMatchObject({ type: "ip4", array: true, member: "type:$extension:ip4r._ip4" });
  expect(api.ip4r.indexes.gist().input).toEqual({ schema: api.schema, type: "ip4r", dimensions: 0 });
  expect(() => createIp4r_2_4({ ...descriptor, apiSupport: { status: "verified", digest: "wrong" } })).toThrow();
  for (const annotation of ip4rAnnotations) expect(annotation.semantics).toMatchObject({ providerAcceptance: "pending", publicExportAcceptance: "pending" });
});
