const evidence = [
  "https://reorg.github.io/pg_repack/",
  "https://github.com/reorg/pg_repack/blob/ver_1.5.2/lib/pg_repack.sql.in",
  "https://github.com/reorg/pg_repack/blob/ver_1.5.2/bin/pg_repack.c",
  "packages/tests/unit/extensions-pg_repack.test.ts",
  "packages/tests/types/extensions-pg_repack.test-d.ts",
  "packages/e2e/integration/extensions-pg_repack.test.ts",
] as const;
const query = {
  authority: "query",
  observability: "external",
  live: "Catalogue helpers and views are not table-revision live queries.",
  nulls: "STRICT helpers reject SQL NULL inputs; non-strict indexdef binds captured NULLs.",
  providerAcceptance: "pending",
  nativeAcceptance: "pending",
  publicExportAcceptance: "pending",
} as const;
const tooling = {
  authority: "operator",
  observability: "external",
  live: "No application SQL or automatic live-query binding",
  rollback:
    "Client writes, toast swap and leftover cleanup are not transactional; acknowledged and unknown effects survive a rolled-back SQL transaction.",
  providerAcceptance: "pending",
  nativeAcceptance: "pending",
  publicExportAcceptance: "pending",
} as const;
const internal = {
  authority: "internal",
  observability: "external",
  live: "Not application SQL",
  providerAcceptance: "pending",
  nativeAcceptance: "pending",
  publicExportAcceptance: "pending",
} as const;
function member(
  id: string,
  disposition: "query" | "tooling" | "internal",
  reason: string,
  semantics: Record<string, string>,
) {
  return { id, disposition, evidence, reason, semantics };
}

/** Exact captured pg_repack 1.5.2 / PG18 member dispositions. Client protocol is the maintenance surface. */
export const pgRepackAnnotations = [
  member(
    "routine:repack.conflicted_triggers(pg_catalog.oid)",
    "query",
    "conflictedTriggers returns SETOF name for an existing repack_trigger on the relation.",
    { ...query, codec: "pg:text:1" },
  ),
  member(
    "routine:repack.create_index_type(pg_catalog.oid,pg_catalog.oid)",
    "tooling",
    "Client-internal CREATE TYPE for the log tuple. Not exported as application SQL; invoked only by the aligned pg_repack binary.",
    { ...tooling, privilege: "Operator session via withPgRepack client protocol" },
  ),
  member(
    "routine:repack.create_log_table(pg_catalog.oid)",
    "tooling",
    "Client-internal log table constructor. Not a JavaScript replay of apply/swap.",
    { ...tooling, privilege: "Operator session via withPgRepack client protocol" },
  ),
  member(
    "routine:repack.create_table(pg_catalog.oid,pg_catalog.name)",
    "tooling",
    "Client-internal copy-table constructor including storage parameters from get_storage_param.",
    { ...tooling, privilege: "Operator session via withPgRepack client protocol" },
  ),
  member(
    "routine:repack.disable_autovacuum(pg_catalog.regclass)",
    "tooling",
    "Client-internal autovacuum disable on the owned copy. Not an application helper.",
    { ...tooling, privilege: "Operator session via withPgRepack client protocol" },
  ),
  member(
    "routine:repack.get_alter_col_storage(pg_catalog.oid)",
    "query",
    "getAlterColStorage returns ALTER TABLE storage clauses or SQL NULL when every column uses the default.",
    { ...query, codec: "pg:text:1" },
  ),
  member(
    "routine:repack.get_assign(pg_catalog.oid,pg_catalog.text)",
    "query",
    "getAssign returns the captured column assignment list for UPDATE replay SQL.",
    { ...query, codec: "pg:text:1" },
  ),
  member(
    "routine:repack.get_columns_for_create_as(pg_catalog.oid)",
    "query",
    "getColumnsForCreateAs returns the SELECT list including dropped-column NULL placeholders.",
    { ...query, codec: "pg:text:1" },
  ),
  member(
    "routine:repack.get_compare_pkey(pg_catalog.oid,pg_catalog.text)",
    "query",
    "getComparePkey returns the primary-key equality predicate used by delete/update replay SQL.",
    { ...query, codec: "pg:text:1" },
  ),
  member(
    "routine:repack.get_create_index_type(pg_catalog.oid,pg_catalog.name)",
    "query",
    "getCreateIndexType returns CREATE TYPE text for the log composite named by the caller.",
    { ...query, codec: "pg:text:1" },
  ),
  member(
    "routine:repack.get_create_trigger(pg_catalog.oid,pg_catalog.oid)",
    "query",
    "getCreateTrigger returns CREATE TRIGGER text that binds repack.repack_trigger to the primary-key columns.",
    { ...query, codec: "pg:text:1" },
  ),
  member(
    "routine:repack.get_drop_columns(pg_catalog.oid,pg_catalog.text)",
    "query",
    "getDropColumns returns ALTER TABLE DROP for dropped attributes on the copy relation.",
    { ...query, codec: "pg:text:1" },
  ),
  member(
    "routine:repack.get_enable_trigger(pg_catalog.oid)",
    "query",
    "getEnableTrigger returns ENABLE ALWAYS TRIGGER repack_trigger for the source relation.",
    { ...query, codec: "pg:text:1" },
  ),
  member(
    "routine:repack.get_index_columns(pg_catalog.oid)",
    "query",
    "getIndexColumns returns the quoted index column list passed to the trigger constructor.",
    { ...query, codec: "pg:text:1" },
  ),
  member(
    "routine:repack.get_order_by(pg_catalog.oid,pg_catalog.oid)",
    "query",
    "getOrderBy returns ORDER BY text from the clustered index, or NULL when none exists.",
    { ...query, codec: "pg:text:1" },
  ),
  member(
    "routine:repack.get_storage_param(pg_catalog.oid)",
    "query",
    "getStorageParam returns WITH-storage text from reloptions, toast reloptions, and the captured oid clause. Native PG18 execution is observed, not patched.",
    { ...query, codec: "pg:text:1" },
  ),
  member(
    "routine:repack.get_table_and_inheritors(pg_catalog.regclass)",
    "query",
    "getTableAndInheritors returns the captured regclass[] of the relation and its inheritors.",
    { ...query, codec: "pg:array:1:,:pg:text:1" },
  ),
  member(
    "routine:repack.oid2text(pg_catalog.oid)",
    "query",
    "oid2text returns schema-qualified regclass text with search_path pinned to pg_catalog.",
    { ...query, codec: "pg:text:1" },
  ),
  member(
    "routine:repack.repack_apply(pg_catalog.cstring,pg_catalog.cstring,pg_catalog.cstring,pg_catalog.cstring,pg_catalog.cstring,pg_catalog.int4)",
    "tooling",
    "Client-internal log apply. JavaScript does not reconstruct peek/insert/delete/update/pop.",
    { ...tooling, privilege: "Operator session via withPgRepack client protocol" },
  ),
  member(
    "routine:repack.repack_drop(pg_catalog.oid,pg_catalog.int4)",
    "tooling",
    "Client-internal leftover drop. Not an application cleanup helper.",
    { ...tooling, privilege: "Operator session via withPgRepack client protocol" },
  ),
  member(
    "routine:repack.repack_index_swap(pg_catalog.oid)",
    "tooling",
    "Client-internal index swap. Not exported as callable application SQL.",
    { ...tooling, privilege: "Operator session via withPgRepack client protocol" },
  ),
  member(
    "routine:repack.repack_indexdef(pg_catalog.oid,pg_catalog.oid,pg_catalog.name,pg_catalog.bool)",
    "query",
    "repackIndexdef returns CREATE INDEX text for the copy, including tablespace and concurrent flags from native C.",
    { ...query, codec: "pg:text:1" },
  ),
  member(
    "routine:repack.repack_swap(pg_catalog.oid)",
    "tooling",
    "Client-internal heap swap. The public operator action is withPgRepack.repack, not this helper.",
    { ...tooling, privilege: "Operator session via withPgRepack client protocol" },
  ),
  member(
    "routine:repack.repack_trigger()",
    "internal",
    "C trigger, not an ordinary SELECT. Ordinary calls surface the native trigger-function error; only CREATE TRIGGER binds it.",
    {
      ...internal,
      privilege: "TRIGGER; SECURITY DEFINER with search_path = pg_catalog, pg_temp",
    },
  ),
  member(
    "routine:repack.version_sql()",
    "query",
    "versionSql returns the SQL-script identity 'pg_repack 1.5.2'. The client compares this string to PROGRAM_NAME+PROGRAM_VERSION.",
    { ...query, codec: "pg:text:1" },
  ),
  member(
    "routine:repack.version()",
    "query",
    "version returns the C-library identity 'pg_repack 1.5.2'. Mismatched client binaries raise the native program/library error.",
    { ...query, codec: "pg:text:1" },
  ),
  member(
    'rule:"_RETURN" on repack.primary_keys',
    "internal",
    "View rewrite rule. Not a callable helper; primaryKeys() reads the view.",
    internal,
  ),
  member(
    'rule:"_RETURN" on repack.tables',
    "internal",
    "View rewrite rule. Not a callable helper; tables() reads the view.",
    internal,
  ),
  member(
    "schema:repack",
    "internal",
    "Fixed CREATE SCHEMA repack. Objects are never relocated to descriptor.schema; relocatable=false.",
    { ...internal, limitation: "ALTER EXTENSION SET SCHEMA fails; WITH SCHEMA does not move qualified repack.* objects" },
  ),
  member(
    "type:repack._primary_keys",
    "query",
    "primaryKeyArrayField stores the captured array of primary_keys composites.",
    { ...query, codec: "pg:array:1:,:pg_repack:1.5.2:primary_keys" },
  ),
  member(
    "type:repack._tables",
    "query",
    "tableArrayField stores the captured array of tables composites.",
    { ...query, codec: "pg:array:1:,:pg_repack:1.5.2:tables" },
  ),
  member(
    "type:repack.primary_keys",
    "query",
    "primaryKeyField stores the captured (indrelid, indexrelid) composite.",
    { ...query, codec: "pg_repack:1.5.2:primary_keys" },
  ),
  member(
    "type:repack.tables",
    "query",
    "tableField stores the captured 24-attribute tables composite.",
    { ...query, codec: "pg_repack:1.5.2:tables" },
  ),
  member(
    "view column:repack.primary_keys.indexrelid",
    "query",
    "primaryKeys().columns.indexrelid is the captured nullable oid.",
    { ...query, codec: "pg:oid:unsigned32:1" },
  ),
  member(
    "view column:repack.primary_keys.indrelid",
    "query",
    "primaryKeys().columns.indrelid is the captured nullable oid.",
    { ...query, codec: "pg:oid:unsigned32:1" },
  ),
  member(
    "view column:repack.tables.alter_col_storage",
    "query",
    "tables().columns.alter_col_storage is the captured nullable text.",
    query,
  ),
  member("view column:repack.tables.ckey", "query", "tables().columns.ckey is the captured nullable clustered-key text.", query),
  member("view column:repack.tables.ckid", "query", "tables().columns.ckid is the captured nullable oid.", query),
  member("view column:repack.tables.copy_data", "query", "tables().columns.copy_data is the captured INSERT...SELECT text.", query),
  member("view column:repack.tables.create_log", "query", "tables().columns.create_log is the captured create_log_table call text.", query),
  member(
    "view column:repack.tables.create_pktype",
    "query",
    "tables().columns.create_pktype is the captured create_index_type call text.",
    query,
  ),
  member(
    "view column:repack.tables.create_table",
    "query",
    "tables().columns.create_table is the captured create_table call text.",
    query,
  ),
  member(
    "view column:repack.tables.create_trigger",
    "query",
    "tables().columns.create_trigger is get_create_trigger text.",
    query,
  ),
  member("view column:repack.tables.delete_log", "query", "tables().columns.delete_log is the captured DELETE FROM log text.", query),
  member("view column:repack.tables.drop_columns", "query", "tables().columns.drop_columns is get_drop_columns text.", query),
  member(
    "view column:repack.tables.enable_trigger",
    "query",
    "tables().columns.enable_trigger is get_enable_trigger text.",
    query,
  ),
  member("view column:repack.tables.lock_table", "query", "tables().columns.lock_table is the captured ACCESS EXCLUSIVE lock text.", query),
  member("view column:repack.tables.pkid", "query", "tables().columns.pkid is the captured nullable primary-key oid.", query),
  member("view column:repack.tables.relid", "query", "tables().columns.relid is the captured relation oid.", query),
  member("view column:repack.tables.relname", "query", "tables().columns.relname is oid2text of the relation.", query),
  member(
    "view column:repack.tables.reltoastidxid",
    "query",
    "tables().columns.reltoastidxid is the captured toast index oid or 0.",
    query,
  ),
  member("view column:repack.tables.reltoastrelid", "query", "tables().columns.reltoastrelid is the captured toast oid.", query),
  member("view column:repack.tables.schemaname", "query", "tables().columns.schemaname is the captured namespace name.", query),
  member("view column:repack.tables.sql_delete", "query", "tables().columns.sql_delete is the captured replay DELETE text.", query),
  member("view column:repack.tables.sql_insert", "query", "tables().columns.sql_insert is the captured replay INSERT text.", query),
  member("view column:repack.tables.sql_peek", "query", "tables().columns.sql_peek is the captured log peek text.", query),
  member("view column:repack.tables.sql_pop", "query", "tables().columns.sql_pop is the captured log pop prefix.", query),
  member("view column:repack.tables.sql_update", "query", "tables().columns.sql_update is the captured replay UPDATE text.", query),
  member(
    "view column:repack.tables.tablespace_orig",
    "query",
    "tables().columns.tablespace_orig is the captured tablespace name.",
    query,
  ),
  member(
    "view:repack.primary_keys",
    "query",
    "primaryKeys(alias) projects the captured primary-key catalogue view.",
    { ...query, codec: "pg_repack:1.5.2:primary_keys" },
  ),
  member("view:repack.tables", "query", "tables(alias) projects the captured maintenance catalogue view.", {
    ...query,
    codec: "pg_repack:1.5.2:tables",
  }),
] as const;
