const evidence = [
  "https://postgis.net/docs/manual-3.6/reference_sfcgal.html",
  "postgis-3.6.4.tar.gz (sha256 ed8dc6679f1e06f7b113592b04cde2a7e00f1b1e681294c8ca2204058990cec6) sfcgal/sfcgal.sql.in and sfcgal/lwgeom_sfcgal.c: SFCGAL library-version gates",
  "packages/tests/unit/extensions-postgis-sfcgal.test.ts: exact 76-member manifest identity, descriptor/dependency rejection, qualified calls, PostGIS geometry codecs and native defaults",
  "packages/e2e/scripts/run-postgis-sfcgal-native-characterization.ts: owned local PG18 oracle (postgis-sfcgal-native.Dockerfile, SFCGAL 2.0.0; postgis-sfcgal-2.3-native.Dockerfile, SFCGAL 2.3.0) with exact digest and one native witness per member",
] as const;
const pending = {
  authority: "query",
  observability: "tables",
  providerAcceptance: "pending",
  publicExportAcceptance: "pending",
} as const;

/** Every captured postgis_sfcgal 3.6.4 member is a public query; native and provider witnesses remain pending. */
export const postgisSfcgalAnnotations = [
  {
    id: "routine:$extension:postgis_sfcgal.cg_2drotate($extension:postgis.geometry,pg_catalog.float8,pg_catalog.float8,pg_catalog.float8)",
    disposition: "query",
    evidence,
    reason: "cg2drotate / sql.functions.cg_2drotate calls the exact captured immutable c routine.",
    semantics: {
      ...pending,
      nulls: "NULL for any NULL argument",
      result: "Geometry | null",
      codec: "postgis:3.6.4:geometry:ewkb-ewkt:1:srid=native:dimensions=native:nullable",
      limitation: "Evaluated natively by PostgreSQL/SFCGAL with no JavaScript geometry fallback; dimensions, SRID and Z/M are PostgreSQL's. PostGIS 3.6.4 source gates this routine on linked SFCGAL >= 2.0.0 and raises a native error otherwise.",
    },
  },
  {
    id: "routine:$extension:postgis_sfcgal.cg_3dalphawrapping($extension:postgis.geometry,pg_catalog.int4,pg_catalog.int4)",
    disposition: "query",
    evidence,
    reason: "cg3dalphawrapping / sql.functions.cg_3dalphawrapping calls the exact captured immutable c routine.",
    semantics: {
      ...pending,
      nulls: "NULL for any NULL argument",
      result: "Geometry | null",
      codec: "postgis:3.6.4:geometry:ewkb-ewkt:1:srid=native:dimensions=native:nullable",
      limitation: "Evaluated natively by PostgreSQL/SFCGAL with no JavaScript geometry fallback; dimensions, SRID and Z/M are PostgreSQL's. PostGIS 3.6.4 source gates this routine on linked SFCGAL >= 2.1.0 and raises a native error otherwise. Omitted trailing arguments use PostgreSQL defaults (0).",
    },
  },
  {
    id: "routine:$extension:postgis_sfcgal.cg_3darea($extension:postgis.geometry)",
    disposition: "query",
    evidence,
    reason: "cg3darea / sql.functions.cg_3darea calls the exact captured immutable c routine.",
    semantics: {
      ...pending,
      nulls: "NULL for any NULL argument",
      result: "number | NonfiniteNumber | null",
      codec: "pg:float8:1:nullable",
      limitation: "Evaluated natively by PostgreSQL/SFCGAL with no JavaScript geometry fallback; dimensions, SRID and Z/M are PostgreSQL's.",
    },
  },
  {
    id: "routine:$extension:postgis_sfcgal.cg_3dbuffer($extension:postgis.geometry,pg_catalog.float8,pg_catalog.int4,pg_catalog.int4)",
    disposition: "query",
    evidence,
    reason: "cg3dbuffer / sql.functions.cg_3dbuffer calls the exact captured immutable c routine.",
    semantics: {
      ...pending,
      nulls: "NULL for any NULL argument",
      result: "Geometry | null",
      codec: "postgis:3.6.4:geometry:ewkb-ewkt:1:srid=native:dimensions=native:nullable",
      limitation: "Evaluated natively by PostgreSQL/SFCGAL with no JavaScript geometry fallback; dimensions, SRID and Z/M are PostgreSQL's. PostGIS 3.6.4 source gates this routine on linked SFCGAL >= 2.0.0 and raises a native error otherwise.",
    },
  },
  {
    id: "routine:$extension:postgis_sfcgal.cg_3dconvexhull($extension:postgis.geometry)",
    disposition: "query",
    evidence,
    reason: "cg3dconvexhull / sql.functions.cg_3dconvexhull calls the exact captured immutable c routine.",
    semantics: {
      ...pending,
      nulls: "NULL for any NULL argument",
      result: "Geometry | null",
      codec: "postgis:3.6.4:geometry:ewkb-ewkt:1:srid=native:dimensions=native:nullable",
      limitation: "Evaluated natively by PostgreSQL/SFCGAL with no JavaScript geometry fallback; dimensions, SRID and Z/M are PostgreSQL's.",
    },
  },
  {
    id: "routine:$extension:postgis_sfcgal.cg_3ddifference($extension:postgis.geometry,$extension:postgis.geometry)",
    disposition: "query",
    evidence,
    reason: "cg3ddifference / sql.functions.cg_3ddifference calls the exact captured immutable c routine.",
    semantics: {
      ...pending,
      nulls: "NULL for any NULL argument",
      result: "Geometry | null",
      codec: "postgis:3.6.4:geometry:ewkb-ewkt:1:srid=native:dimensions=native:nullable",
      limitation: "Evaluated natively by PostgreSQL/SFCGAL with no JavaScript geometry fallback; dimensions, SRID and Z/M are PostgreSQL's.",
    },
  },
  {
    id: "routine:$extension:postgis_sfcgal.cg_3ddistance($extension:postgis.geometry,$extension:postgis.geometry)",
    disposition: "query",
    evidence,
    reason: "cg3ddistance / sql.functions.cg_3ddistance calls the exact captured immutable c routine.",
    semantics: {
      ...pending,
      nulls: "NULL for any NULL argument",
      result: "number | NonfiniteNumber | null",
      codec: "pg:float8:1:nullable",
      limitation: "Evaluated natively by PostgreSQL/SFCGAL with no JavaScript geometry fallback; dimensions, SRID and Z/M are PostgreSQL's.",
    },
  },
  {
    id: "routine:$extension:postgis_sfcgal.cg_3dintersection($extension:postgis.geometry,$extension:postgis.geometry)",
    disposition: "query",
    evidence,
    reason: "cg3dintersection / sql.functions.cg_3dintersection calls the exact captured immutable c routine.",
    semantics: {
      ...pending,
      nulls: "NULL for any NULL argument",
      result: "Geometry | null",
      codec: "postgis:3.6.4:geometry:ewkb-ewkt:1:srid=native:dimensions=native:nullable",
      limitation: "Evaluated natively by PostgreSQL/SFCGAL with no JavaScript geometry fallback; dimensions, SRID and Z/M are PostgreSQL's.",
    },
  },
  {
    id: "routine:$extension:postgis_sfcgal.cg_3dintersects($extension:postgis.geometry,$extension:postgis.geometry)",
    disposition: "query",
    evidence,
    reason: "cg3dintersects / sql.functions.cg_3dintersects calls the exact captured immutable c routine.",
    semantics: {
      ...pending,
      nulls: "NULL for any NULL argument",
      result: "boolean | null",
      codec: "pg:bool:1:nullable",
      limitation: "Evaluated natively by PostgreSQL/SFCGAL with no JavaScript geometry fallback; dimensions, SRID and Z/M are PostgreSQL's.",
    },
  },
  {
    id: "routine:$extension:postgis_sfcgal.cg_3drotate($extension:postgis.geometry,pg_catalog.float8,pg_catalog.float8,pg_catalog.float8,pg_catalog.float8)",
    disposition: "query",
    evidence,
    reason: "cg3drotate / sql.functions.cg_3drotate calls the exact captured immutable c routine.",
    semantics: {
      ...pending,
      nulls: "NULL for any NULL argument",
      result: "Geometry | null",
      codec: "postgis:3.6.4:geometry:ewkb-ewkt:1:srid=native:dimensions=native:nullable",
      limitation: "Evaluated natively by PostgreSQL/SFCGAL with no JavaScript geometry fallback; dimensions, SRID and Z/M are PostgreSQL's. PostGIS 3.6.4 source gates this routine on linked SFCGAL >= 2.0.0 and raises a native error otherwise.",
    },
  },
  {
    id: "routine:$extension:postgis_sfcgal.cg_3dscale($extension:postgis.geometry,pg_catalog.float8,pg_catalog.float8,pg_catalog.float8)",
    disposition: "query",
    evidence,
    reason: "cg3dscale / sql.functions.cg_3dscale calls the exact captured immutable c routine.",
    semantics: {
      ...pending,
      nulls: "NULL for any NULL argument",
      result: "Geometry | null",
      codec: "postgis:3.6.4:geometry:ewkb-ewkt:1:srid=native:dimensions=native:nullable",
      limitation: "Evaluated natively by PostgreSQL/SFCGAL with no JavaScript geometry fallback; dimensions, SRID and Z/M are PostgreSQL's. PostGIS 3.6.4 source gates this routine on linked SFCGAL >= 2.0.0 and raises a native error otherwise.",
    },
  },
  {
    id: "routine:$extension:postgis_sfcgal.cg_3dscalearoundcenter($extension:postgis.geometry,pg_catalog.float8,pg_catalog.float8,pg_catalog.float8,pg_catalog.float8,pg_catalog.float8,pg_catalog.float8)",
    disposition: "query",
    evidence,
    reason: "cg3dscalearoundcenter / sql.functions.cg_3dscalearoundcenter calls the exact captured immutable c routine.",
    semantics: {
      ...pending,
      nulls: "NULL for any NULL argument",
      result: "Geometry | null",
      codec: "postgis:3.6.4:geometry:ewkb-ewkt:1:srid=native:dimensions=native:nullable",
      limitation: "Evaluated natively by PostgreSQL/SFCGAL with no JavaScript geometry fallback; dimensions, SRID and Z/M are PostgreSQL's. PostGIS 3.6.4 source gates this routine on linked SFCGAL >= 2.0.0 and raises a native error otherwise.",
    },
  },
  {
    id: "routine:$extension:postgis_sfcgal.cg_3dtranslate($extension:postgis.geometry,pg_catalog.float8,pg_catalog.float8,pg_catalog.float8)",
    disposition: "query",
    evidence,
    reason: "cg3dtranslate / sql.functions.cg_3dtranslate calls the exact captured immutable c routine.",
    semantics: {
      ...pending,
      nulls: "NULL for any NULL argument",
      result: "Geometry | null",
      codec: "postgis:3.6.4:geometry:ewkb-ewkt:1:srid=native:dimensions=native:nullable",
      limitation: "Evaluated natively by PostgreSQL/SFCGAL with no JavaScript geometry fallback; dimensions, SRID and Z/M are PostgreSQL's. PostGIS 3.6.4 source gates this routine on linked SFCGAL >= 2.0.0 and raises a native error otherwise.",
    },
  },
  {
    id: "routine:$extension:postgis_sfcgal.cg_3dunion($extension:postgis.geometry)",
    disposition: "query",
    evidence,
    reason: "cg3dunion / sql.functions.cg_3dunion calls the exact captured immutable internal routine.",
    semantics: {
      ...pending,
      nulls: "PostgreSQL-defined",
      result: "Geometry | null",
      codec: "postgis:3.6.4:geometry:ewkb-ewkt:1:srid=native:dimensions=native:nullable",
      limitation: "Evaluated natively by PostgreSQL/SFCGAL with no JavaScript geometry fallback; dimensions, SRID and Z/M are PostgreSQL's.",
    },
  },
  {
    id: "routine:$extension:postgis_sfcgal.cg_3dunion($extension:postgis.geometry,$extension:postgis.geometry)",
    disposition: "query",
    evidence,
    reason: "cg3dunion / sql.functions.cg_3dunion calls the exact captured immutable c routine.",
    semantics: {
      ...pending,
      nulls: "NULL for any NULL argument",
      result: "Geometry | null",
      codec: "postgis:3.6.4:geometry:ewkb-ewkt:1:srid=native:dimensions=native:nullable",
      limitation: "Evaluated natively by PostgreSQL/SFCGAL with no JavaScript geometry fallback; dimensions, SRID and Z/M are PostgreSQL's.",
    },
  },
  {
    id: "routine:$extension:postgis_sfcgal.cg_alphashape($extension:postgis.geometry,pg_catalog.float8,pg_catalog.bool)",
    disposition: "query",
    evidence,
    reason: "cgAlphashape / sql.functions.cg_alphashape calls the exact captured immutable c routine.",
    semantics: {
      ...pending,
      nulls: "NULL for any NULL argument",
      result: "Geometry | null",
      codec: "postgis:3.6.4:geometry:ewkb-ewkt:1:srid=native:dimensions=native:nullable",
      limitation: "Evaluated natively by PostgreSQL/SFCGAL with no JavaScript geometry fallback; dimensions, SRID and Z/M are PostgreSQL's. Omitted trailing arguments use PostgreSQL defaults (1.0, false).",
    },
  },
  {
    id: "routine:$extension:postgis_sfcgal.cg_approxconvexpartition($extension:postgis.geometry)",
    disposition: "query",
    evidence,
    reason: "cgApproxconvexpartition / sql.functions.cg_approxconvexpartition calls the exact captured immutable c routine.",
    semantics: {
      ...pending,
      nulls: "NULL for any NULL argument",
      result: "Geometry | null",
      codec: "postgis:3.6.4:geometry:ewkb-ewkt:1:srid=native:dimensions=native:nullable",
      limitation: "Evaluated natively by PostgreSQL/SFCGAL with no JavaScript geometry fallback; dimensions, SRID and Z/M are PostgreSQL's. PostGIS 3.6.4 source gates this routine on linked SFCGAL >= 1.5.0 and raises a native error otherwise.",
    },
  },
  {
    id: "routine:$extension:postgis_sfcgal.cg_approximatemedialaxis($extension:postgis.geometry)",
    disposition: "query",
    evidence,
    reason: "cgApproximatemedialaxis / sql.functions.cg_approximatemedialaxis calls the exact captured immutable c routine.",
    semantics: {
      ...pending,
      nulls: "NULL for any NULL argument",
      result: "Geometry | null",
      codec: "postgis:3.6.4:geometry:ewkb-ewkt:1:srid=native:dimensions=native:nullable",
      limitation: "Evaluated natively by PostgreSQL/SFCGAL with no JavaScript geometry fallback; dimensions, SRID and Z/M are PostgreSQL's.",
    },
  },
  {
    id: "routine:$extension:postgis_sfcgal.cg_area($extension:postgis.geometry)",
    disposition: "query",
    evidence,
    reason: "cgArea / sql.functions.cg_area calls the exact captured immutable c routine.",
    semantics: {
      ...pending,
      nulls: "NULL for any NULL argument",
      result: "number | NonfiniteNumber | null",
      codec: "pg:float8:1:nullable",
      limitation: "Evaluated natively by PostgreSQL/SFCGAL with no JavaScript geometry fallback; dimensions, SRID and Z/M are PostgreSQL's.",
    },
  },
  {
    id: "routine:$extension:postgis_sfcgal.cg_constraineddelaunaytriangles($extension:postgis.geometry)",
    disposition: "query",
    evidence,
    reason: "cgConstraineddelaunaytriangles / sql.functions.cg_constraineddelaunaytriangles calls the exact captured immutable c routine.",
    semantics: {
      ...pending,
      nulls: "NULL for any NULL argument",
      result: "Geometry | null",
      codec: "postgis:3.6.4:geometry:ewkb-ewkt:1:srid=native:dimensions=native:nullable",
      limitation: "Evaluated natively by PostgreSQL/SFCGAL with no JavaScript geometry fallback; dimensions, SRID and Z/M are PostgreSQL's.",
    },
  },
  {
    id: "routine:$extension:postgis_sfcgal.cg_difference($extension:postgis.geometry,$extension:postgis.geometry)",
    disposition: "query",
    evidence,
    reason: "cgDifference / sql.functions.cg_difference calls the exact captured immutable c routine.",
    semantics: {
      ...pending,
      nulls: "NULL for any NULL argument",
      result: "Geometry | null",
      codec: "postgis:3.6.4:geometry:ewkb-ewkt:1:srid=native:dimensions=native:nullable",
      limitation: "Evaluated natively by PostgreSQL/SFCGAL with no JavaScript geometry fallback; dimensions, SRID and Z/M are PostgreSQL's.",
    },
  },
  {
    id: "routine:$extension:postgis_sfcgal.cg_distance($extension:postgis.geometry,$extension:postgis.geometry)",
    disposition: "query",
    evidence,
    reason: "cgDistance / sql.functions.cg_distance calls the exact captured immutable c routine.",
    semantics: {
      ...pending,
      nulls: "NULL for any NULL argument",
      result: "number | NonfiniteNumber | null",
      codec: "pg:float8:1:nullable",
      limitation: "Evaluated natively by PostgreSQL/SFCGAL with no JavaScript geometry fallback; dimensions, SRID and Z/M are PostgreSQL's.",
    },
  },
  {
    id: "routine:$extension:postgis_sfcgal.cg_extrude($extension:postgis.geometry,pg_catalog.float8,pg_catalog.float8,pg_catalog.float8)",
    disposition: "query",
    evidence,
    reason: "cgExtrude / sql.functions.cg_extrude calls the exact captured immutable c routine.",
    semantics: {
      ...pending,
      nulls: "NULL for any NULL argument",
      result: "Geometry | null",
      codec: "postgis:3.6.4:geometry:ewkb-ewkt:1:srid=native:dimensions=native:nullable",
      limitation: "Evaluated natively by PostgreSQL/SFCGAL with no JavaScript geometry fallback; dimensions, SRID and Z/M are PostgreSQL's.",
    },
  },
  {
    id: "routine:$extension:postgis_sfcgal.cg_extrudestraightskeleton($extension:postgis.geometry,pg_catalog.float8,pg_catalog.float8)",
    disposition: "query",
    evidence,
    reason: "cgExtrudestraightskeleton / sql.functions.cg_extrudestraightskeleton calls the exact captured immutable c routine.",
    semantics: {
      ...pending,
      nulls: "NULL for any NULL argument",
      result: "Geometry | null",
      codec: "postgis:3.6.4:geometry:ewkb-ewkt:1:srid=native:dimensions=native:nullable",
      limitation: "Evaluated natively by PostgreSQL/SFCGAL with no JavaScript geometry fallback; dimensions, SRID and Z/M are PostgreSQL's. PostGIS 3.6.4 source gates this routine on linked SFCGAL >= 1.5.0 and raises a native error otherwise. Omitted trailing arguments use PostgreSQL defaults (0.0).",
    },
  },
  {
    id: "routine:$extension:postgis_sfcgal.cg_forcelhr($extension:postgis.geometry)",
    disposition: "query",
    evidence,
    reason: "cgForcelhr / sql.functions.cg_forcelhr calls the exact captured immutable c routine.",
    semantics: {
      ...pending,
      nulls: "NULL for any NULL argument",
      result: "Geometry | null",
      codec: "postgis:3.6.4:geometry:ewkb-ewkt:1:srid=native:dimensions=native:nullable",
      limitation: "Evaluated natively by PostgreSQL/SFCGAL with no JavaScript geometry fallback; dimensions, SRID and Z/M are PostgreSQL's.",
    },
  },
  {
    id: "routine:$extension:postgis_sfcgal.cg_greeneapproxconvexpartition($extension:postgis.geometry)",
    disposition: "query",
    evidence,
    reason: "cgGreeneapproxconvexpartition / sql.functions.cg_greeneapproxconvexpartition calls the exact captured immutable c routine.",
    semantics: {
      ...pending,
      nulls: "NULL for any NULL argument",
      result: "Geometry | null",
      codec: "postgis:3.6.4:geometry:ewkb-ewkt:1:srid=native:dimensions=native:nullable",
      limitation: "Evaluated natively by PostgreSQL/SFCGAL with no JavaScript geometry fallback; dimensions, SRID and Z/M are PostgreSQL's. PostGIS 3.6.4 source gates this routine on linked SFCGAL >= 1.5.0 and raises a native error otherwise.",
    },
  },
  {
    id: "routine:$extension:postgis_sfcgal.cg_intersection($extension:postgis.geometry,$extension:postgis.geometry)",
    disposition: "query",
    evidence,
    reason: "cgIntersection / sql.functions.cg_intersection calls the exact captured immutable c routine.",
    semantics: {
      ...pending,
      nulls: "NULL for any NULL argument",
      result: "Geometry | null",
      codec: "postgis:3.6.4:geometry:ewkb-ewkt:1:srid=native:dimensions=native:nullable",
      limitation: "Evaluated natively by PostgreSQL/SFCGAL with no JavaScript geometry fallback; dimensions, SRID and Z/M are PostgreSQL's.",
    },
  },
  {
    id: "routine:$extension:postgis_sfcgal.cg_intersects($extension:postgis.geometry,$extension:postgis.geometry)",
    disposition: "query",
    evidence,
    reason: "cgIntersects / sql.functions.cg_intersects calls the exact captured immutable c routine.",
    semantics: {
      ...pending,
      nulls: "NULL for any NULL argument",
      result: "boolean | null",
      codec: "pg:bool:1:nullable",
      limitation: "Evaluated natively by PostgreSQL/SFCGAL with no JavaScript geometry fallback; dimensions, SRID and Z/M are PostgreSQL's.",
    },
  },
  {
    id: "routine:$extension:postgis_sfcgal.cg_isplanar($extension:postgis.geometry)",
    disposition: "query",
    evidence,
    reason: "cgIsplanar / sql.functions.cg_isplanar calls the exact captured immutable c routine.",
    semantics: {
      ...pending,
      nulls: "NULL for any NULL argument",
      result: "boolean | null",
      codec: "pg:bool:1:nullable",
      limitation: "Evaluated natively by PostgreSQL/SFCGAL with no JavaScript geometry fallback; dimensions, SRID and Z/M are PostgreSQL's.",
    },
  },
  {
    id: "routine:$extension:postgis_sfcgal.cg_issolid($extension:postgis.geometry)",
    disposition: "query",
    evidence,
    reason: "cgIssolid / sql.functions.cg_issolid calls the exact captured immutable c routine.",
    semantics: {
      ...pending,
      nulls: "NULL for any NULL argument",
      result: "boolean | null",
      codec: "pg:bool:1:nullable",
      limitation: "Evaluated natively by PostgreSQL/SFCGAL with no JavaScript geometry fallback; dimensions, SRID and Z/M are PostgreSQL's.",
    },
  },
  {
    id: "routine:$extension:postgis_sfcgal.cg_makesolid($extension:postgis.geometry)",
    disposition: "query",
    evidence,
    reason: "cgMakesolid / sql.functions.cg_makesolid calls the exact captured immutable c routine.",
    semantics: {
      ...pending,
      nulls: "NULL for any NULL argument",
      result: "Geometry | null",
      codec: "postgis:3.6.4:geometry:ewkb-ewkt:1:srid=native:dimensions=native:nullable",
      limitation: "Evaluated natively by PostgreSQL/SFCGAL with no JavaScript geometry fallback; dimensions, SRID and Z/M are PostgreSQL's.",
    },
  },
  {
    id: "routine:$extension:postgis_sfcgal.cg_minkowskisum($extension:postgis.geometry,$extension:postgis.geometry)",
    disposition: "query",
    evidence,
    reason: "cgMinkowskisum / sql.functions.cg_minkowskisum calls the exact captured immutable c routine.",
    semantics: {
      ...pending,
      nulls: "NULL for any NULL argument",
      result: "Geometry | null",
      codec: "postgis:3.6.4:geometry:ewkb-ewkt:1:srid=native:dimensions=native:nullable",
      limitation: "Evaluated natively by PostgreSQL/SFCGAL with no JavaScript geometry fallback; dimensions, SRID and Z/M are PostgreSQL's.",
    },
  },
  {
    id: "routine:$extension:postgis_sfcgal.cg_optimalalphashape($extension:postgis.geometry,pg_catalog.bool,pg_catalog.int4)",
    disposition: "query",
    evidence,
    reason: "cgOptimalalphashape / sql.functions.cg_optimalalphashape calls the exact captured immutable c routine.",
    semantics: {
      ...pending,
      nulls: "NULL for any NULL argument",
      result: "Geometry | null",
      codec: "postgis:3.6.4:geometry:ewkb-ewkt:1:srid=native:dimensions=native:nullable",
      limitation: "Evaluated natively by PostgreSQL/SFCGAL with no JavaScript geometry fallback; dimensions, SRID and Z/M are PostgreSQL's. Omitted trailing arguments use PostgreSQL defaults (false, 1).",
    },
  },
  {
    id: "routine:$extension:postgis_sfcgal.cg_optimalconvexpartition($extension:postgis.geometry)",
    disposition: "query",
    evidence,
    reason: "cgOptimalconvexpartition / sql.functions.cg_optimalconvexpartition calls the exact captured immutable c routine.",
    semantics: {
      ...pending,
      nulls: "NULL for any NULL argument",
      result: "Geometry | null",
      codec: "postgis:3.6.4:geometry:ewkb-ewkt:1:srid=native:dimensions=native:nullable",
      limitation: "Evaluated natively by PostgreSQL/SFCGAL with no JavaScript geometry fallback; dimensions, SRID and Z/M are PostgreSQL's. PostGIS 3.6.4 source gates this routine on linked SFCGAL >= 1.5.0 and raises a native error otherwise.",
    },
  },
  {
    id: "routine:$extension:postgis_sfcgal.cg_orientation($extension:postgis.geometry)",
    disposition: "query",
    evidence,
    reason: "cgOrientation / sql.functions.cg_orientation calls the exact captured immutable c routine.",
    semantics: {
      ...pending,
      nulls: "NULL for any NULL argument",
      result: "number | null",
      codec: "pg:int4:1:nullable",
      limitation: "Evaluated natively by PostgreSQL/SFCGAL with no JavaScript geometry fallback; dimensions, SRID and Z/M are PostgreSQL's.",
    },
  },
  {
    id: "routine:$extension:postgis_sfcgal.cg_rotate($extension:postgis.geometry,pg_catalog.float8)",
    disposition: "query",
    evidence,
    reason: "cgRotate / sql.functions.cg_rotate calls the exact captured immutable c routine.",
    semantics: {
      ...pending,
      nulls: "NULL for any NULL argument",
      result: "Geometry | null",
      codec: "postgis:3.6.4:geometry:ewkb-ewkt:1:srid=native:dimensions=native:nullable",
      limitation: "Evaluated natively by PostgreSQL/SFCGAL with no JavaScript geometry fallback; dimensions, SRID and Z/M are PostgreSQL's. PostGIS 3.6.4 source gates this routine on linked SFCGAL >= 2.0.0 and raises a native error otherwise.",
    },
  },
  {
    id: "routine:$extension:postgis_sfcgal.cg_rotatex($extension:postgis.geometry,pg_catalog.float8)",
    disposition: "query",
    evidence,
    reason: "cgRotatex / sql.functions.cg_rotatex calls the exact captured immutable c routine.",
    semantics: {
      ...pending,
      nulls: "NULL for any NULL argument",
      result: "Geometry | null",
      codec: "postgis:3.6.4:geometry:ewkb-ewkt:1:srid=native:dimensions=native:nullable",
      limitation: "Evaluated natively by PostgreSQL/SFCGAL with no JavaScript geometry fallback; dimensions, SRID and Z/M are PostgreSQL's. PostGIS 3.6.4 source gates this routine on linked SFCGAL >= 2.0.0 and raises a native error otherwise.",
    },
  },
  {
    id: "routine:$extension:postgis_sfcgal.cg_rotatey($extension:postgis.geometry,pg_catalog.float8)",
    disposition: "query",
    evidence,
    reason: "cgRotatey / sql.functions.cg_rotatey calls the exact captured immutable c routine.",
    semantics: {
      ...pending,
      nulls: "NULL for any NULL argument",
      result: "Geometry | null",
      codec: "postgis:3.6.4:geometry:ewkb-ewkt:1:srid=native:dimensions=native:nullable",
      limitation: "Evaluated natively by PostgreSQL/SFCGAL with no JavaScript geometry fallback; dimensions, SRID and Z/M are PostgreSQL's. PostGIS 3.6.4 source gates this routine on linked SFCGAL >= 2.0.0 and raises a native error otherwise.",
    },
  },
  {
    id: "routine:$extension:postgis_sfcgal.cg_rotatez($extension:postgis.geometry,pg_catalog.float8)",
    disposition: "query",
    evidence,
    reason: "cgRotatez / sql.functions.cg_rotatez calls the exact captured immutable c routine.",
    semantics: {
      ...pending,
      nulls: "NULL for any NULL argument",
      result: "Geometry | null",
      codec: "postgis:3.6.4:geometry:ewkb-ewkt:1:srid=native:dimensions=native:nullable",
      limitation: "Evaluated natively by PostgreSQL/SFCGAL with no JavaScript geometry fallback; dimensions, SRID and Z/M are PostgreSQL's. PostGIS 3.6.4 source gates this routine on linked SFCGAL >= 2.0.0 and raises a native error otherwise.",
    },
  },
  {
    id: "routine:$extension:postgis_sfcgal.cg_scale($extension:postgis.geometry,pg_catalog.float8)",
    disposition: "query",
    evidence,
    reason: "cgScale / sql.functions.cg_scale calls the exact captured immutable c routine.",
    semantics: {
      ...pending,
      nulls: "NULL for any NULL argument",
      result: "Geometry | null",
      codec: "postgis:3.6.4:geometry:ewkb-ewkt:1:srid=native:dimensions=native:nullable",
      limitation: "Evaluated natively by PostgreSQL/SFCGAL with no JavaScript geometry fallback; dimensions, SRID and Z/M are PostgreSQL's. PostGIS 3.6.4 source gates this routine on linked SFCGAL >= 2.0.0 and raises a native error otherwise.",
    },
  },
  {
    id: "routine:$extension:postgis_sfcgal.cg_simplify($extension:postgis.geometry,pg_catalog.float8,pg_catalog.bool)",
    disposition: "query",
    evidence,
    reason: "cgSimplify / sql.functions.cg_simplify calls the exact captured immutable c routine.",
    semantics: {
      ...pending,
      nulls: "NULL for any NULL argument",
      result: "Geometry | null",
      codec: "postgis:3.6.4:geometry:ewkb-ewkt:1:srid=native:dimensions=native:nullable",
      limitation: "Evaluated natively by PostgreSQL/SFCGAL with no JavaScript geometry fallback; dimensions, SRID and Z/M are PostgreSQL's. PostGIS 3.6.4 source gates this routine on linked SFCGAL >= 2.1.0 and raises a native error otherwise. Omitted trailing arguments use PostgreSQL defaults (false).",
    },
  },
  {
    id: "routine:$extension:postgis_sfcgal.cg_straightskeleton($extension:postgis.geometry,pg_catalog.bool)",
    disposition: "query",
    evidence,
    reason: "cgStraightskeleton / sql.functions.cg_straightskeleton calls the exact captured immutable c routine.",
    semantics: {
      ...pending,
      nulls: "NULL for any NULL argument",
      result: "Geometry | null",
      codec: "postgis:3.6.4:geometry:ewkb-ewkt:1:srid=native:dimensions=native:nullable",
      limitation: "Evaluated natively by PostgreSQL/SFCGAL with no JavaScript geometry fallback; dimensions, SRID and Z/M are PostgreSQL's. Omitted trailing arguments use PostgreSQL defaults (false).",
    },
  },
  {
    id: "routine:$extension:postgis_sfcgal.cg_straightskeletonpartition($extension:postgis.geometry,pg_catalog.bool)",
    disposition: "query",
    evidence,
    reason: "cgStraightskeletonpartition / sql.functions.cg_straightskeletonpartition calls the exact captured immutable c routine.",
    semantics: {
      ...pending,
      nulls: "NULL for any NULL argument",
      result: "Geometry | null",
      codec: "postgis:3.6.4:geometry:ewkb-ewkt:1:srid=native:dimensions=native:nullable",
      limitation: "Evaluated natively by PostgreSQL/SFCGAL with no JavaScript geometry fallback; dimensions, SRID and Z/M are PostgreSQL's. PostGIS 3.6.4 source gates this routine on linked SFCGAL >= 2.0.0 and raises a native error otherwise.",
    },
  },
  {
    id: "routine:$extension:postgis_sfcgal.cg_tesselate($extension:postgis.geometry)",
    disposition: "query",
    evidence,
    reason: "cgTesselate / sql.functions.cg_tesselate calls the exact captured immutable c routine.",
    semantics: {
      ...pending,
      nulls: "NULL for any NULL argument",
      result: "Geometry | null",
      codec: "postgis:3.6.4:geometry:ewkb-ewkt:1:srid=native:dimensions=native:nullable",
      limitation: "Evaluated natively by PostgreSQL/SFCGAL with no JavaScript geometry fallback; dimensions, SRID and Z/M are PostgreSQL's.",
    },
  },
  {
    id: "routine:$extension:postgis_sfcgal.cg_translate($extension:postgis.geometry,pg_catalog.float8,pg_catalog.float8)",
    disposition: "query",
    evidence,
    reason: "cgTranslate / sql.functions.cg_translate calls the exact captured immutable c routine.",
    semantics: {
      ...pending,
      nulls: "NULL for any NULL argument",
      result: "Geometry | null",
      codec: "postgis:3.6.4:geometry:ewkb-ewkt:1:srid=native:dimensions=native:nullable",
      limitation: "Evaluated natively by PostgreSQL/SFCGAL with no JavaScript geometry fallback; dimensions, SRID and Z/M are PostgreSQL's. PostGIS 3.6.4 source gates this routine on linked SFCGAL >= 2.0.0 and raises a native error otherwise.",
    },
  },
  {
    id: "routine:$extension:postgis_sfcgal.cg_triangulate($extension:postgis.geometry)",
    disposition: "query",
    evidence,
    reason: "cgTriangulate / sql.functions.cg_triangulate calls the exact captured immutable c routine.",
    semantics: {
      ...pending,
      nulls: "NULL for any NULL argument",
      result: "Geometry | null",
      codec: "postgis:3.6.4:geometry:ewkb-ewkt:1:srid=native:dimensions=native:nullable",
      limitation: "Evaluated natively by PostgreSQL/SFCGAL with no JavaScript geometry fallback; dimensions, SRID and Z/M are PostgreSQL's.",
    },
  },
  {
    id: "routine:$extension:postgis_sfcgal.cg_union($extension:postgis.geometry)",
    disposition: "query",
    evidence,
    reason: "cgUnion / sql.functions.cg_union calls the exact captured immutable internal routine.",
    semantics: {
      ...pending,
      nulls: "PostgreSQL-defined",
      result: "Geometry | null",
      codec: "postgis:3.6.4:geometry:ewkb-ewkt:1:srid=native:dimensions=native:nullable",
      limitation: "Evaluated natively by PostgreSQL/SFCGAL with no JavaScript geometry fallback; dimensions, SRID and Z/M are PostgreSQL's.",
    },
  },
  {
    id: "routine:$extension:postgis_sfcgal.cg_union($extension:postgis.geometry,$extension:postgis.geometry)",
    disposition: "query",
    evidence,
    reason: "cgUnion / sql.functions.cg_union calls the exact captured immutable c routine.",
    semantics: {
      ...pending,
      nulls: "NULL for any NULL argument",
      result: "Geometry | null",
      codec: "postgis:3.6.4:geometry:ewkb-ewkt:1:srid=native:dimensions=native:nullable",
      limitation: "Evaluated natively by PostgreSQL/SFCGAL with no JavaScript geometry fallback; dimensions, SRID and Z/M are PostgreSQL's.",
    },
  },
  {
    id: "routine:$extension:postgis_sfcgal.cg_visibility($extension:postgis.geometry,$extension:postgis.geometry)",
    disposition: "query",
    evidence,
    reason: "cgVisibility / sql.functions.cg_visibility calls the exact captured immutable c routine.",
    semantics: {
      ...pending,
      nulls: "NULL for any NULL argument",
      result: "Geometry | null",
      codec: "postgis:3.6.4:geometry:ewkb-ewkt:1:srid=native:dimensions=native:nullable",
      limitation: "Evaluated natively by PostgreSQL/SFCGAL with no JavaScript geometry fallback; dimensions, SRID and Z/M are PostgreSQL's. PostGIS 3.6.4 source gates this routine on linked SFCGAL >= 1.5.0 and raises a native error otherwise.",
    },
  },
  {
    id: "routine:$extension:postgis_sfcgal.cg_visibility($extension:postgis.geometry,$extension:postgis.geometry,$extension:postgis.geometry)",
    disposition: "query",
    evidence,
    reason: "cgVisibility / sql.functions.cg_visibility calls the exact captured immutable c routine.",
    semantics: {
      ...pending,
      nulls: "NULL for any NULL argument",
      result: "Geometry | null",
      codec: "postgis:3.6.4:geometry:ewkb-ewkt:1:srid=native:dimensions=native:nullable",
      limitation: "Evaluated natively by PostgreSQL/SFCGAL with no JavaScript geometry fallback; dimensions, SRID and Z/M are PostgreSQL's. PostGIS 3.6.4 source gates this routine on linked SFCGAL >= 1.5.0 and raises a native error otherwise.",
    },
  },
  {
    id: "routine:$extension:postgis_sfcgal.cg_volume($extension:postgis.geometry)",
    disposition: "query",
    evidence,
    reason: "cgVolume / sql.functions.cg_volume calls the exact captured immutable c routine.",
    semantics: {
      ...pending,
      nulls: "NULL for any NULL argument",
      result: "number | NonfiniteNumber | null",
      codec: "pg:float8:1:nullable",
      limitation: "Evaluated natively by PostgreSQL/SFCGAL with no JavaScript geometry fallback; dimensions, SRID and Z/M are PostgreSQL's.",
    },
  },
  {
    id: "routine:$extension:postgis_sfcgal.cg_ymonotonepartition($extension:postgis.geometry)",
    disposition: "query",
    evidence,
    reason: "cgYmonotonepartition / sql.functions.cg_ymonotonepartition calls the exact captured immutable c routine.",
    semantics: {
      ...pending,
      nulls: "NULL for any NULL argument",
      result: "Geometry | null",
      codec: "postgis:3.6.4:geometry:ewkb-ewkt:1:srid=native:dimensions=native:nullable",
      limitation: "Evaluated natively by PostgreSQL/SFCGAL with no JavaScript geometry fallback; dimensions, SRID and Z/M are PostgreSQL's.",
    },
  },
  {
    id: "routine:$extension:postgis_sfcgal.postgis_sfcgal_full_version()",
    disposition: "query",
    evidence,
    reason: "postgisSfcgalFullVersion / sql.functions.postgis_sfcgal_full_version calls the exact captured immutable c routine.",
    semantics: {
      ...pending,
      nulls: "PostgreSQL-defined",
      result: "string | null",
      codec: "pg:text:1:nullable",
      limitation: "Evaluated natively by PostgreSQL/SFCGAL with no JavaScript geometry fallback; dimensions, SRID and Z/M are PostgreSQL's.",
    },
  },
  {
    id: "routine:$extension:postgis_sfcgal.postgis_sfcgal_noop($extension:postgis.geometry)",
    disposition: "query",
    evidence,
    reason: "postgisSfcgalNoop / sql.functions.postgis_sfcgal_noop calls the exact captured immutable c routine.",
    semantics: {
      ...pending,
      nulls: "NULL for any NULL argument",
      result: "Geometry | null",
      codec: "postgis:3.6.4:geometry:ewkb-ewkt:1:srid=native:dimensions=native:nullable",
      limitation: "Evaluated natively by PostgreSQL/SFCGAL with no JavaScript geometry fallback; dimensions, SRID and Z/M are PostgreSQL's.",
    },
  },
  {
    id: "routine:$extension:postgis_sfcgal.postgis_sfcgal_scripts_installed()",
    disposition: "query",
    evidence,
    reason: "postgisSfcgalScriptsInstalled / sql.functions.postgis_sfcgal_scripts_installed calls the exact captured immutable sql routine.",
    semantics: {
      ...pending,
      nulls: "PostgreSQL-defined",
      result: "string | null",
      codec: "pg:text:1:nullable",
      limitation: "Evaluated natively by PostgreSQL/SFCGAL with no JavaScript geometry fallback; dimensions, SRID and Z/M are PostgreSQL's.",
    },
  },
  {
    id: "routine:$extension:postgis_sfcgal.postgis_sfcgal_version()",
    disposition: "query",
    evidence,
    reason: "postgisSfcgalVersion / sql.functions.postgis_sfcgal_version calls the exact captured immutable c routine.",
    semantics: {
      ...pending,
      nulls: "PostgreSQL-defined",
      result: "string | null",
      codec: "pg:text:1:nullable",
      limitation: "Evaluated natively by PostgreSQL/SFCGAL with no JavaScript geometry fallback; dimensions, SRID and Z/M are PostgreSQL's.",
    },
  },
  {
    id: "routine:$extension:postgis_sfcgal.st_3darea($extension:postgis.geometry)",
    disposition: "query",
    evidence,
    reason: "st3darea / sql.functions.st_3darea calls the exact captured immutable sql routine.",
    semantics: {
      ...pending,
      nulls: "PostgreSQL-defined",
      result: "number | NonfiniteNumber | null",
      codec: "pg:float8:1:nullable",
      limitation: "Evaluated natively by PostgreSQL/SFCGAL with no JavaScript geometry fallback; dimensions, SRID and Z/M are PostgreSQL's. Deprecated SQL wrapper: it calls _postgis_deprecate and its CG_* replacement unqualified, so PostgreSQL resolves it only with both the postgis and postgis_sfcgal schemas on search_path (otherwise SQLSTATE 42883), and then raises a deprecation WARNING.",
    },
  },
  {
    id: "routine:$extension:postgis_sfcgal.st_3dconvexhull($extension:postgis.geometry)",
    disposition: "query",
    evidence,
    reason: "st3dconvexhull / sql.functions.st_3dconvexhull calls the exact captured immutable sql routine.",
    semantics: {
      ...pending,
      nulls: "PostgreSQL-defined",
      result: "Geometry | null",
      codec: "postgis:3.6.4:geometry:ewkb-ewkt:1:srid=native:dimensions=native:nullable",
      limitation: "Evaluated natively by PostgreSQL/SFCGAL with no JavaScript geometry fallback; dimensions, SRID and Z/M are PostgreSQL's. PostGIS 3.6.4 source gates this routine on linked SFCGAL >= 1.4.1 and raises a native error otherwise. Deprecated SQL wrapper: it calls _postgis_deprecate and its CG_* replacement unqualified, so PostgreSQL resolves it only with both the postgis and postgis_sfcgal schemas on search_path (otherwise SQLSTATE 42883), and then raises a deprecation WARNING.",
    },
  },
  {
    id: "routine:$extension:postgis_sfcgal.st_3ddifference($extension:postgis.geometry,$extension:postgis.geometry)",
    disposition: "query",
    evidence,
    reason: "st3ddifference / sql.functions.st_3ddifference calls the exact captured immutable sql routine.",
    semantics: {
      ...pending,
      nulls: "PostgreSQL-defined",
      result: "Geometry | null",
      codec: "postgis:3.6.4:geometry:ewkb-ewkt:1:srid=native:dimensions=native:nullable",
      limitation: "Evaluated natively by PostgreSQL/SFCGAL with no JavaScript geometry fallback; dimensions, SRID and Z/M are PostgreSQL's. Deprecated SQL wrapper: it calls _postgis_deprecate and its CG_* replacement unqualified, so PostgreSQL resolves it only with both the postgis and postgis_sfcgal schemas on search_path (otherwise SQLSTATE 42883), and then raises a deprecation WARNING.",
    },
  },
  {
    id: "routine:$extension:postgis_sfcgal.st_3dintersection($extension:postgis.geometry,$extension:postgis.geometry)",
    disposition: "query",
    evidence,
    reason: "st3dintersection / sql.functions.st_3dintersection calls the exact captured immutable sql routine.",
    semantics: {
      ...pending,
      nulls: "PostgreSQL-defined",
      result: "Geometry | null",
      codec: "postgis:3.6.4:geometry:ewkb-ewkt:1:srid=native:dimensions=native:nullable",
      limitation: "Evaluated natively by PostgreSQL/SFCGAL with no JavaScript geometry fallback; dimensions, SRID and Z/M are PostgreSQL's. Deprecated SQL wrapper: it calls _postgis_deprecate and its CG_* replacement unqualified, so PostgreSQL resolves it only with both the postgis and postgis_sfcgal schemas on search_path (otherwise SQLSTATE 42883), and then raises a deprecation WARNING.",
    },
  },
  {
    id: "routine:$extension:postgis_sfcgal.st_3dunion($extension:postgis.geometry)",
    disposition: "query",
    evidence,
    reason: "st3dunion / sql.functions.st_3dunion calls the exact captured immutable internal routine.",
    semantics: {
      ...pending,
      nulls: "PostgreSQL-defined",
      result: "Geometry | null",
      codec: "postgis:3.6.4:geometry:ewkb-ewkt:1:srid=native:dimensions=native:nullable",
      limitation: "Evaluated natively by PostgreSQL/SFCGAL with no JavaScript geometry fallback; dimensions, SRID and Z/M are PostgreSQL's.",
    },
  },
  {
    id: "routine:$extension:postgis_sfcgal.st_3dunion($extension:postgis.geometry,$extension:postgis.geometry)",
    disposition: "query",
    evidence,
    reason: "st3dunion / sql.functions.st_3dunion calls the exact captured immutable sql routine.",
    semantics: {
      ...pending,
      nulls: "PostgreSQL-defined",
      result: "Geometry | null",
      codec: "postgis:3.6.4:geometry:ewkb-ewkt:1:srid=native:dimensions=native:nullable",
      limitation: "Evaluated natively by PostgreSQL/SFCGAL with no JavaScript geometry fallback; dimensions, SRID and Z/M are PostgreSQL's. Deprecated SQL wrapper: it calls _postgis_deprecate and its CG_* replacement unqualified, so PostgreSQL resolves it only with both the postgis and postgis_sfcgal schemas on search_path (otherwise SQLSTATE 42883), and then raises a deprecation WARNING.",
    },
  },
  {
    id: "routine:$extension:postgis_sfcgal.st_alphashape($extension:postgis.geometry,pg_catalog.float8,pg_catalog.bool)",
    disposition: "query",
    evidence,
    reason: "stAlphashape / sql.functions.st_alphashape calls the exact captured immutable sql routine.",
    semantics: {
      ...pending,
      nulls: "PostgreSQL-defined",
      result: "Geometry | null",
      codec: "postgis:3.6.4:geometry:ewkb-ewkt:1:srid=native:dimensions=native:nullable",
      limitation: "Evaluated natively by PostgreSQL/SFCGAL with no JavaScript geometry fallback; dimensions, SRID and Z/M are PostgreSQL's. PostGIS 3.6.4 source gates this routine on linked SFCGAL >= 1.4.1 and raises a native error otherwise. Omitted trailing arguments use PostgreSQL defaults (1.0, false). Deprecated SQL wrapper: it calls _postgis_deprecate and its CG_* replacement unqualified, so PostgreSQL resolves it only with both the postgis and postgis_sfcgal schemas on search_path (otherwise SQLSTATE 42883), and then raises a deprecation WARNING.",
    },
  },
  {
    id: "routine:$extension:postgis_sfcgal.st_approximatemedialaxis($extension:postgis.geometry)",
    disposition: "query",
    evidence,
    reason: "stApproximatemedialaxis / sql.functions.st_approximatemedialaxis calls the exact captured immutable sql routine.",
    semantics: {
      ...pending,
      nulls: "PostgreSQL-defined",
      result: "Geometry | null",
      codec: "postgis:3.6.4:geometry:ewkb-ewkt:1:srid=native:dimensions=native:nullable",
      limitation: "Evaluated natively by PostgreSQL/SFCGAL with no JavaScript geometry fallback; dimensions, SRID and Z/M are PostgreSQL's. Deprecated SQL wrapper: it calls _postgis_deprecate and its CG_* replacement unqualified, so PostgreSQL resolves it only with both the postgis and postgis_sfcgal schemas on search_path (otherwise SQLSTATE 42883), and then raises a deprecation WARNING.",
    },
  },
  {
    id: "routine:$extension:postgis_sfcgal.st_constraineddelaunaytriangles($extension:postgis.geometry)",
    disposition: "query",
    evidence,
    reason: "stConstraineddelaunaytriangles / sql.functions.st_constraineddelaunaytriangles calls the exact captured immutable sql routine.",
    semantics: {
      ...pending,
      nulls: "PostgreSQL-defined",
      result: "Geometry | null",
      codec: "postgis:3.6.4:geometry:ewkb-ewkt:1:srid=native:dimensions=native:nullable",
      limitation: "Evaluated natively by PostgreSQL/SFCGAL with no JavaScript geometry fallback; dimensions, SRID and Z/M are PostgreSQL's. Deprecated SQL wrapper: it calls _postgis_deprecate and its CG_* replacement unqualified, so PostgreSQL resolves it only with both the postgis and postgis_sfcgal schemas on search_path (otherwise SQLSTATE 42883), and then raises a deprecation WARNING.",
    },
  },
  {
    id: "routine:$extension:postgis_sfcgal.st_extrude($extension:postgis.geometry,pg_catalog.float8,pg_catalog.float8,pg_catalog.float8)",
    disposition: "query",
    evidence,
    reason: "stExtrude / sql.functions.st_extrude calls the exact captured immutable sql routine.",
    semantics: {
      ...pending,
      nulls: "PostgreSQL-defined",
      result: "Geometry | null",
      codec: "postgis:3.6.4:geometry:ewkb-ewkt:1:srid=native:dimensions=native:nullable",
      limitation: "Evaluated natively by PostgreSQL/SFCGAL with no JavaScript geometry fallback; dimensions, SRID and Z/M are PostgreSQL's. Deprecated SQL wrapper: it calls _postgis_deprecate and its CG_* replacement unqualified, so PostgreSQL resolves it only with both the postgis and postgis_sfcgal schemas on search_path (otherwise SQLSTATE 42883), and then raises a deprecation WARNING.",
    },
  },
  {
    id: "routine:$extension:postgis_sfcgal.st_forcelhr($extension:postgis.geometry)",
    disposition: "query",
    evidence,
    reason: "stForcelhr / sql.functions.st_forcelhr calls the exact captured immutable sql routine.",
    semantics: {
      ...pending,
      nulls: "PostgreSQL-defined",
      result: "Geometry | null",
      codec: "postgis:3.6.4:geometry:ewkb-ewkt:1:srid=native:dimensions=native:nullable",
      limitation: "Evaluated natively by PostgreSQL/SFCGAL with no JavaScript geometry fallback; dimensions, SRID and Z/M are PostgreSQL's. Deprecated SQL wrapper: it calls _postgis_deprecate and its CG_* replacement unqualified, so PostgreSQL resolves it only with both the postgis and postgis_sfcgal schemas on search_path (otherwise SQLSTATE 42883), and then raises a deprecation WARNING.",
    },
  },
  {
    id: "routine:$extension:postgis_sfcgal.st_isplanar($extension:postgis.geometry)",
    disposition: "query",
    evidence,
    reason: "stIsplanar / sql.functions.st_isplanar calls the exact captured immutable sql routine.",
    semantics: {
      ...pending,
      nulls: "PostgreSQL-defined",
      result: "boolean | null",
      codec: "pg:bool:1:nullable",
      limitation: "Evaluated natively by PostgreSQL/SFCGAL with no JavaScript geometry fallback; dimensions, SRID and Z/M are PostgreSQL's. Deprecated SQL wrapper: it calls _postgis_deprecate and its CG_* replacement unqualified, so PostgreSQL resolves it only with both the postgis and postgis_sfcgal schemas on search_path (otherwise SQLSTATE 42883), and then raises a deprecation WARNING.",
    },
  },
  {
    id: "routine:$extension:postgis_sfcgal.st_issolid($extension:postgis.geometry)",
    disposition: "query",
    evidence,
    reason: "stIssolid / sql.functions.st_issolid calls the exact captured immutable sql routine.",
    semantics: {
      ...pending,
      nulls: "PostgreSQL-defined",
      result: "boolean | null",
      codec: "pg:bool:1:nullable",
      limitation: "Evaluated natively by PostgreSQL/SFCGAL with no JavaScript geometry fallback; dimensions, SRID and Z/M are PostgreSQL's. Deprecated SQL wrapper: it calls _postgis_deprecate and its CG_* replacement unqualified, so PostgreSQL resolves it only with both the postgis and postgis_sfcgal schemas on search_path (otherwise SQLSTATE 42883), and then raises a deprecation WARNING.",
    },
  },
  {
    id: "routine:$extension:postgis_sfcgal.st_makesolid($extension:postgis.geometry)",
    disposition: "query",
    evidence,
    reason: "stMakesolid / sql.functions.st_makesolid calls the exact captured immutable sql routine.",
    semantics: {
      ...pending,
      nulls: "PostgreSQL-defined",
      result: "Geometry | null",
      codec: "postgis:3.6.4:geometry:ewkb-ewkt:1:srid=native:dimensions=native:nullable",
      limitation: "Evaluated natively by PostgreSQL/SFCGAL with no JavaScript geometry fallback; dimensions, SRID and Z/M are PostgreSQL's. Deprecated SQL wrapper: it calls _postgis_deprecate and its CG_* replacement unqualified, so PostgreSQL resolves it only with both the postgis and postgis_sfcgal schemas on search_path (otherwise SQLSTATE 42883), and then raises a deprecation WARNING.",
    },
  },
  {
    id: "routine:$extension:postgis_sfcgal.st_minkowskisum($extension:postgis.geometry,$extension:postgis.geometry)",
    disposition: "query",
    evidence,
    reason: "stMinkowskisum / sql.functions.st_minkowskisum calls the exact captured immutable sql routine.",
    semantics: {
      ...pending,
      nulls: "PostgreSQL-defined",
      result: "Geometry | null",
      codec: "postgis:3.6.4:geometry:ewkb-ewkt:1:srid=native:dimensions=native:nullable",
      limitation: "Evaluated natively by PostgreSQL/SFCGAL with no JavaScript geometry fallback; dimensions, SRID and Z/M are PostgreSQL's. PostGIS 3.6.4 source gates this routine on linked SFCGAL >= 1.3.8 and raises a native error otherwise. Deprecated SQL wrapper: it calls _postgis_deprecate and its CG_* replacement unqualified, so PostgreSQL resolves it only with both the postgis and postgis_sfcgal schemas on search_path (otherwise SQLSTATE 42883), and then raises a deprecation WARNING.",
    },
  },
  {
    id: "routine:$extension:postgis_sfcgal.st_optimalalphashape($extension:postgis.geometry,pg_catalog.bool,pg_catalog.int4)",
    disposition: "query",
    evidence,
    reason: "stOptimalalphashape / sql.functions.st_optimalalphashape calls the exact captured immutable sql routine.",
    semantics: {
      ...pending,
      nulls: "PostgreSQL-defined",
      result: "Geometry | null",
      codec: "postgis:3.6.4:geometry:ewkb-ewkt:1:srid=native:dimensions=native:nullable",
      limitation: "Evaluated natively by PostgreSQL/SFCGAL with no JavaScript geometry fallback; dimensions, SRID and Z/M are PostgreSQL's. PostGIS 3.6.4 source gates this routine on linked SFCGAL >= 1.5.0 and raises a native error otherwise. Omitted trailing arguments use PostgreSQL defaults (false, 1). Deprecated SQL wrapper: it calls _postgis_deprecate and its CG_* replacement unqualified, so PostgreSQL resolves it only with both the postgis and postgis_sfcgal schemas on search_path (otherwise SQLSTATE 42883), and then raises a deprecation WARNING.",
    },
  },
  {
    id: "routine:$extension:postgis_sfcgal.st_orientation($extension:postgis.geometry)",
    disposition: "query",
    evidence,
    reason: "stOrientation / sql.functions.st_orientation calls the exact captured immutable sql routine.",
    semantics: {
      ...pending,
      nulls: "PostgreSQL-defined",
      result: "number | null",
      codec: "pg:int4:1:nullable",
      limitation: "Evaluated natively by PostgreSQL/SFCGAL with no JavaScript geometry fallback; dimensions, SRID and Z/M are PostgreSQL's. Deprecated SQL wrapper: it calls _postgis_deprecate and its CG_* replacement unqualified, so PostgreSQL resolves it only with both the postgis and postgis_sfcgal schemas on search_path (otherwise SQLSTATE 42883), and then raises a deprecation WARNING.",
    },
  },
  {
    id: "routine:$extension:postgis_sfcgal.st_straightskeleton($extension:postgis.geometry)",
    disposition: "query",
    evidence,
    reason: "stStraightskeleton / sql.functions.st_straightskeleton calls the exact captured immutable sql routine.",
    semantics: {
      ...pending,
      nulls: "PostgreSQL-defined",
      result: "Geometry | null",
      codec: "postgis:3.6.4:geometry:ewkb-ewkt:1:srid=native:dimensions=native:nullable",
      limitation: "Evaluated natively by PostgreSQL/SFCGAL with no JavaScript geometry fallback; dimensions, SRID and Z/M are PostgreSQL's. Deprecated SQL wrapper: it calls _postgis_deprecate and its CG_* replacement unqualified, so PostgreSQL resolves it only with both the postgis and postgis_sfcgal schemas on search_path (otherwise SQLSTATE 42883), and then raises a deprecation WARNING.",
    },
  },
  {
    id: "routine:$extension:postgis_sfcgal.st_tesselate($extension:postgis.geometry)",
    disposition: "query",
    evidence,
    reason: "stTesselate / sql.functions.st_tesselate calls the exact captured immutable sql routine.",
    semantics: {
      ...pending,
      nulls: "PostgreSQL-defined",
      result: "Geometry | null",
      codec: "postgis:3.6.4:geometry:ewkb-ewkt:1:srid=native:dimensions=native:nullable",
      limitation: "Evaluated natively by PostgreSQL/SFCGAL with no JavaScript geometry fallback; dimensions, SRID and Z/M are PostgreSQL's. Deprecated SQL wrapper: it calls _postgis_deprecate and its CG_* replacement unqualified, so PostgreSQL resolves it only with both the postgis and postgis_sfcgal schemas on search_path (otherwise SQLSTATE 42883), and then raises a deprecation WARNING.",
    },
  },
  {
    id: "routine:$extension:postgis_sfcgal.st_volume($extension:postgis.geometry)",
    disposition: "query",
    evidence,
    reason: "stVolume / sql.functions.st_volume calls the exact captured immutable sql routine.",
    semantics: {
      ...pending,
      nulls: "PostgreSQL-defined",
      result: "number | NonfiniteNumber | null",
      codec: "pg:float8:1:nullable",
      limitation: "Evaluated natively by PostgreSQL/SFCGAL with no JavaScript geometry fallback; dimensions, SRID and Z/M are PostgreSQL's. Deprecated SQL wrapper: it calls _postgis_deprecate and its CG_* replacement unqualified, so PostgreSQL resolves it only with both the postgis and postgis_sfcgal schemas on search_path (otherwise SQLSTATE 42883), and then raises a deprecation WARNING.",
    },
  },
] as const;
