/** Exact seg 1.4 dispositions; acceptance remains pending until host native and isolated-consumer proofs. */
export const segAnnotations = [
  {
    id: 'function of access method:function 1 ("$extension:seg".seg, "$extension:seg".seg) of "$extension:seg".gist_seg_ops USING gist',
    disposition: "internal",
    reason:
      "Backend callback or access-method catalog wiring; exercised only through the owning native type or index path.",
    evidence: [
      "apps/loom/src/tooling/extensions/manifests/seg.json",
      "https://www.postgresql.org/docs/18/seg.html",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/seg.c",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/segparse.y",
      "apps/loom/src/core/extensions/adapters/seg.ts",
      "packages/tests/unit/extensions-seg.test.ts",
      "packages/tests/types/extensions-seg.test-d.ts",
      "packages/e2e/integration/extensions-seg.test.ts",
    ],
    semantics: {
      providerAcceptance: "pending",
      publicExportAcceptance: "pending",
      parent: '"$extension:seg".gist_seg_ops USING gist',
    },
  },
  {
    id: 'function of access method:function 1 ("$extension:seg".seg, "$extension:seg".seg) of "$extension:seg".seg_ops USING btree',
    disposition: "internal",
    reason:
      "Backend callback or access-method catalog wiring; exercised only through the owning native type or index path.",
    evidence: [
      "apps/loom/src/tooling/extensions/manifests/seg.json",
      "https://www.postgresql.org/docs/18/seg.html",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/seg.c",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/segparse.y",
      "apps/loom/src/core/extensions/adapters/seg.ts",
      "packages/tests/unit/extensions-seg.test.ts",
      "packages/tests/types/extensions-seg.test-d.ts",
      "packages/e2e/integration/extensions-seg.test.ts",
    ],
    semantics: {
      providerAcceptance: "pending",
      publicExportAcceptance: "pending",
      parent: '"$extension:seg".seg_ops USING btree',
    },
  },
  {
    id: 'function of access method:function 2 ("$extension:seg".seg, "$extension:seg".seg) of "$extension:seg".gist_seg_ops USING gist',
    disposition: "internal",
    reason:
      "Backend callback or access-method catalog wiring; exercised only through the owning native type or index path.",
    evidence: [
      "apps/loom/src/tooling/extensions/manifests/seg.json",
      "https://www.postgresql.org/docs/18/seg.html",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/seg.c",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/segparse.y",
      "apps/loom/src/core/extensions/adapters/seg.ts",
      "packages/tests/unit/extensions-seg.test.ts",
      "packages/tests/types/extensions-seg.test-d.ts",
      "packages/e2e/integration/extensions-seg.test.ts",
    ],
    semantics: {
      providerAcceptance: "pending",
      publicExportAcceptance: "pending",
      parent: '"$extension:seg".gist_seg_ops USING gist',
    },
  },
  {
    id: 'function of access method:function 5 ("$extension:seg".seg, "$extension:seg".seg) of "$extension:seg".gist_seg_ops USING gist',
    disposition: "internal",
    reason:
      "Backend callback or access-method catalog wiring; exercised only through the owning native type or index path.",
    evidence: [
      "apps/loom/src/tooling/extensions/manifests/seg.json",
      "https://www.postgresql.org/docs/18/seg.html",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/seg.c",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/segparse.y",
      "apps/loom/src/core/extensions/adapters/seg.ts",
      "packages/tests/unit/extensions-seg.test.ts",
      "packages/tests/types/extensions-seg.test-d.ts",
      "packages/e2e/integration/extensions-seg.test.ts",
    ],
    semantics: {
      providerAcceptance: "pending",
      publicExportAcceptance: "pending",
      parent: '"$extension:seg".gist_seg_ops USING gist',
    },
  },
  {
    id: 'function of access method:function 6 ("$extension:seg".seg, "$extension:seg".seg) of "$extension:seg".gist_seg_ops USING gist',
    disposition: "internal",
    reason:
      "Backend callback or access-method catalog wiring; exercised only through the owning native type or index path.",
    evidence: [
      "apps/loom/src/tooling/extensions/manifests/seg.json",
      "https://www.postgresql.org/docs/18/seg.html",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/seg.c",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/segparse.y",
      "apps/loom/src/core/extensions/adapters/seg.ts",
      "packages/tests/unit/extensions-seg.test.ts",
      "packages/tests/types/extensions-seg.test-d.ts",
      "packages/e2e/integration/extensions-seg.test.ts",
    ],
    semantics: {
      providerAcceptance: "pending",
      publicExportAcceptance: "pending",
      parent: '"$extension:seg".gist_seg_ops USING gist',
    },
  },
  {
    id: 'function of access method:function 7 ("$extension:seg".seg, "$extension:seg".seg) of "$extension:seg".gist_seg_ops USING gist',
    disposition: "internal",
    reason:
      "Backend callback or access-method catalog wiring; exercised only through the owning native type or index path.",
    evidence: [
      "apps/loom/src/tooling/extensions/manifests/seg.json",
      "https://www.postgresql.org/docs/18/seg.html",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/seg.c",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/segparse.y",
      "apps/loom/src/core/extensions/adapters/seg.ts",
      "packages/tests/unit/extensions-seg.test.ts",
      "packages/tests/types/extensions-seg.test-d.ts",
      "packages/e2e/integration/extensions-seg.test.ts",
    ],
    semantics: {
      providerAcceptance: "pending",
      publicExportAcceptance: "pending",
      parent: '"$extension:seg".gist_seg_ops USING gist',
    },
  },
  {
    id: "opclass:$extension:seg.gist_seg_ops/gist",
    disposition: "schema",
    reason:
      "Native seg type, dimensional array or qualified index operator class; decimal endpoint spelling retains precision and certainty.",
    evidence: [
      "apps/loom/src/tooling/extensions/manifests/seg.json",
      "https://www.postgresql.org/docs/18/seg.html",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/seg.c",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/segparse.y",
      "apps/loom/src/core/extensions/adapters/seg.ts",
      "packages/tests/unit/extensions-seg.test.ts",
      "packages/tests/types/extensions-seg.test-d.ts",
      "packages/e2e/integration/extensions-seg.test.ts",
    ],
    semantics: {
      providerAcceptance: "pending",
      publicExportAcceptance: "pending",
    },
  },
  {
    id: "opclass:$extension:seg.seg_ops/btree",
    disposition: "schema",
    reason:
      "Native seg type, dimensional array or qualified index operator class; decimal endpoint spelling retains precision and certainty.",
    evidence: [
      "apps/loom/src/tooling/extensions/manifests/seg.json",
      "https://www.postgresql.org/docs/18/seg.html",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/seg.c",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/segparse.y",
      "apps/loom/src/core/extensions/adapters/seg.ts",
      "packages/tests/unit/extensions-seg.test.ts",
      "packages/tests/types/extensions-seg.test-d.ts",
      "packages/e2e/integration/extensions-seg.test.ts",
    ],
    semantics: {
      providerAcceptance: "pending",
      publicExportAcceptance: "pending",
    },
  },
  {
    id: 'operator of access method:operator 1 ("$extension:seg".seg, "$extension:seg".seg) of "$extension:seg".gist_seg_ops USING gist',
    disposition: "internal",
    reason:
      "Backend callback or access-method catalog wiring; exercised only through the owning native type or index path.",
    evidence: [
      "apps/loom/src/tooling/extensions/manifests/seg.json",
      "https://www.postgresql.org/docs/18/seg.html",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/seg.c",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/segparse.y",
      "apps/loom/src/core/extensions/adapters/seg.ts",
      "packages/tests/unit/extensions-seg.test.ts",
      "packages/tests/types/extensions-seg.test-d.ts",
      "packages/e2e/integration/extensions-seg.test.ts",
    ],
    semantics: {
      providerAcceptance: "pending",
      publicExportAcceptance: "pending",
      parent: '"$extension:seg".gist_seg_ops USING gist',
    },
  },
  {
    id: 'operator of access method:operator 1 ("$extension:seg".seg, "$extension:seg".seg) of "$extension:seg".seg_ops USING btree',
    disposition: "internal",
    reason:
      "Backend callback or access-method catalog wiring; exercised only through the owning native type or index path.",
    evidence: [
      "apps/loom/src/tooling/extensions/manifests/seg.json",
      "https://www.postgresql.org/docs/18/seg.html",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/seg.c",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/segparse.y",
      "apps/loom/src/core/extensions/adapters/seg.ts",
      "packages/tests/unit/extensions-seg.test.ts",
      "packages/tests/types/extensions-seg.test-d.ts",
      "packages/e2e/integration/extensions-seg.test.ts",
    ],
    semantics: {
      providerAcceptance: "pending",
      publicExportAcceptance: "pending",
      parent: '"$extension:seg".seg_ops USING btree',
    },
  },
  {
    id: 'operator of access method:operator 2 ("$extension:seg".seg, "$extension:seg".seg) of "$extension:seg".gist_seg_ops USING gist',
    disposition: "internal",
    reason:
      "Backend callback or access-method catalog wiring; exercised only through the owning native type or index path.",
    evidence: [
      "apps/loom/src/tooling/extensions/manifests/seg.json",
      "https://www.postgresql.org/docs/18/seg.html",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/seg.c",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/segparse.y",
      "apps/loom/src/core/extensions/adapters/seg.ts",
      "packages/tests/unit/extensions-seg.test.ts",
      "packages/tests/types/extensions-seg.test-d.ts",
      "packages/e2e/integration/extensions-seg.test.ts",
    ],
    semantics: {
      providerAcceptance: "pending",
      publicExportAcceptance: "pending",
      parent: '"$extension:seg".gist_seg_ops USING gist',
    },
  },
  {
    id: 'operator of access method:operator 2 ("$extension:seg".seg, "$extension:seg".seg) of "$extension:seg".seg_ops USING btree',
    disposition: "internal",
    reason:
      "Backend callback or access-method catalog wiring; exercised only through the owning native type or index path.",
    evidence: [
      "apps/loom/src/tooling/extensions/manifests/seg.json",
      "https://www.postgresql.org/docs/18/seg.html",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/seg.c",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/segparse.y",
      "apps/loom/src/core/extensions/adapters/seg.ts",
      "packages/tests/unit/extensions-seg.test.ts",
      "packages/tests/types/extensions-seg.test-d.ts",
      "packages/e2e/integration/extensions-seg.test.ts",
    ],
    semantics: {
      providerAcceptance: "pending",
      publicExportAcceptance: "pending",
      parent: '"$extension:seg".seg_ops USING btree',
    },
  },
  {
    id: 'operator of access method:operator 3 ("$extension:seg".seg, "$extension:seg".seg) of "$extension:seg".gist_seg_ops USING gist',
    disposition: "internal",
    reason:
      "Backend callback or access-method catalog wiring; exercised only through the owning native type or index path.",
    evidence: [
      "apps/loom/src/tooling/extensions/manifests/seg.json",
      "https://www.postgresql.org/docs/18/seg.html",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/seg.c",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/segparse.y",
      "apps/loom/src/core/extensions/adapters/seg.ts",
      "packages/tests/unit/extensions-seg.test.ts",
      "packages/tests/types/extensions-seg.test-d.ts",
      "packages/e2e/integration/extensions-seg.test.ts",
    ],
    semantics: {
      providerAcceptance: "pending",
      publicExportAcceptance: "pending",
      parent: '"$extension:seg".gist_seg_ops USING gist',
    },
  },
  {
    id: 'operator of access method:operator 3 ("$extension:seg".seg, "$extension:seg".seg) of "$extension:seg".seg_ops USING btree',
    disposition: "internal",
    reason:
      "Backend callback or access-method catalog wiring; exercised only through the owning native type or index path.",
    evidence: [
      "apps/loom/src/tooling/extensions/manifests/seg.json",
      "https://www.postgresql.org/docs/18/seg.html",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/seg.c",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/segparse.y",
      "apps/loom/src/core/extensions/adapters/seg.ts",
      "packages/tests/unit/extensions-seg.test.ts",
      "packages/tests/types/extensions-seg.test-d.ts",
      "packages/e2e/integration/extensions-seg.test.ts",
    ],
    semantics: {
      providerAcceptance: "pending",
      publicExportAcceptance: "pending",
      parent: '"$extension:seg".seg_ops USING btree',
    },
  },
  {
    id: 'operator of access method:operator 4 ("$extension:seg".seg, "$extension:seg".seg) of "$extension:seg".gist_seg_ops USING gist',
    disposition: "internal",
    reason:
      "Backend callback or access-method catalog wiring; exercised only through the owning native type or index path.",
    evidence: [
      "apps/loom/src/tooling/extensions/manifests/seg.json",
      "https://www.postgresql.org/docs/18/seg.html",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/seg.c",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/segparse.y",
      "apps/loom/src/core/extensions/adapters/seg.ts",
      "packages/tests/unit/extensions-seg.test.ts",
      "packages/tests/types/extensions-seg.test-d.ts",
      "packages/e2e/integration/extensions-seg.test.ts",
    ],
    semantics: {
      providerAcceptance: "pending",
      publicExportAcceptance: "pending",
      parent: '"$extension:seg".gist_seg_ops USING gist',
    },
  },
  {
    id: 'operator of access method:operator 4 ("$extension:seg".seg, "$extension:seg".seg) of "$extension:seg".seg_ops USING btree',
    disposition: "internal",
    reason:
      "Backend callback or access-method catalog wiring; exercised only through the owning native type or index path.",
    evidence: [
      "apps/loom/src/tooling/extensions/manifests/seg.json",
      "https://www.postgresql.org/docs/18/seg.html",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/seg.c",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/segparse.y",
      "apps/loom/src/core/extensions/adapters/seg.ts",
      "packages/tests/unit/extensions-seg.test.ts",
      "packages/tests/types/extensions-seg.test-d.ts",
      "packages/e2e/integration/extensions-seg.test.ts",
    ],
    semantics: {
      providerAcceptance: "pending",
      publicExportAcceptance: "pending",
      parent: '"$extension:seg".seg_ops USING btree',
    },
  },
  {
    id: 'operator of access method:operator 5 ("$extension:seg".seg, "$extension:seg".seg) of "$extension:seg".gist_seg_ops USING gist',
    disposition: "internal",
    reason:
      "Backend callback or access-method catalog wiring; exercised only through the owning native type or index path.",
    evidence: [
      "apps/loom/src/tooling/extensions/manifests/seg.json",
      "https://www.postgresql.org/docs/18/seg.html",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/seg.c",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/segparse.y",
      "apps/loom/src/core/extensions/adapters/seg.ts",
      "packages/tests/unit/extensions-seg.test.ts",
      "packages/tests/types/extensions-seg.test-d.ts",
      "packages/e2e/integration/extensions-seg.test.ts",
    ],
    semantics: {
      providerAcceptance: "pending",
      publicExportAcceptance: "pending",
      parent: '"$extension:seg".gist_seg_ops USING gist',
    },
  },
  {
    id: 'operator of access method:operator 5 ("$extension:seg".seg, "$extension:seg".seg) of "$extension:seg".seg_ops USING btree',
    disposition: "internal",
    reason:
      "Backend callback or access-method catalog wiring; exercised only through the owning native type or index path.",
    evidence: [
      "apps/loom/src/tooling/extensions/manifests/seg.json",
      "https://www.postgresql.org/docs/18/seg.html",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/seg.c",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/segparse.y",
      "apps/loom/src/core/extensions/adapters/seg.ts",
      "packages/tests/unit/extensions-seg.test.ts",
      "packages/tests/types/extensions-seg.test-d.ts",
      "packages/e2e/integration/extensions-seg.test.ts",
    ],
    semantics: {
      providerAcceptance: "pending",
      publicExportAcceptance: "pending",
      parent: '"$extension:seg".seg_ops USING btree',
    },
  },
  {
    id: 'operator of access method:operator 6 ("$extension:seg".seg, "$extension:seg".seg) of "$extension:seg".gist_seg_ops USING gist',
    disposition: "internal",
    reason:
      "Backend callback or access-method catalog wiring; exercised only through the owning native type or index path.",
    evidence: [
      "apps/loom/src/tooling/extensions/manifests/seg.json",
      "https://www.postgresql.org/docs/18/seg.html",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/seg.c",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/segparse.y",
      "apps/loom/src/core/extensions/adapters/seg.ts",
      "packages/tests/unit/extensions-seg.test.ts",
      "packages/tests/types/extensions-seg.test-d.ts",
      "packages/e2e/integration/extensions-seg.test.ts",
    ],
    semantics: {
      providerAcceptance: "pending",
      publicExportAcceptance: "pending",
      parent: '"$extension:seg".gist_seg_ops USING gist',
    },
  },
  {
    id: 'operator of access method:operator 7 ("$extension:seg".seg, "$extension:seg".seg) of "$extension:seg".gist_seg_ops USING gist',
    disposition: "internal",
    reason:
      "Backend callback or access-method catalog wiring; exercised only through the owning native type or index path.",
    evidence: [
      "apps/loom/src/tooling/extensions/manifests/seg.json",
      "https://www.postgresql.org/docs/18/seg.html",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/seg.c",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/segparse.y",
      "apps/loom/src/core/extensions/adapters/seg.ts",
      "packages/tests/unit/extensions-seg.test.ts",
      "packages/tests/types/extensions-seg.test-d.ts",
      "packages/e2e/integration/extensions-seg.test.ts",
    ],
    semantics: {
      providerAcceptance: "pending",
      publicExportAcceptance: "pending",
      parent: '"$extension:seg".gist_seg_ops USING gist',
    },
  },
  {
    id: 'operator of access method:operator 8 ("$extension:seg".seg, "$extension:seg".seg) of "$extension:seg".gist_seg_ops USING gist',
    disposition: "internal",
    reason:
      "Backend callback or access-method catalog wiring; exercised only through the owning native type or index path.",
    evidence: [
      "apps/loom/src/tooling/extensions/manifests/seg.json",
      "https://www.postgresql.org/docs/18/seg.html",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/seg.c",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/segparse.y",
      "apps/loom/src/core/extensions/adapters/seg.ts",
      "packages/tests/unit/extensions-seg.test.ts",
      "packages/tests/types/extensions-seg.test-d.ts",
      "packages/e2e/integration/extensions-seg.test.ts",
    ],
    semantics: {
      providerAcceptance: "pending",
      publicExportAcceptance: "pending",
      parent: '"$extension:seg".gist_seg_ops USING gist',
    },
  },
  {
    id: "operator:$extension:seg.@>($extension:seg.seg,$extension:seg.seg)",
    disposition: "query",
    reason:
      "Exact native SQL operator or routine with validated seg endpoints, native float4 results and strict-null codecs.",
    evidence: [
      "apps/loom/src/tooling/extensions/manifests/seg.json",
      "https://www.postgresql.org/docs/18/seg.html",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/seg.c",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/segparse.y",
      "apps/loom/src/core/extensions/adapters/seg.ts",
      "packages/tests/unit/extensions-seg.test.ts",
      "packages/tests/types/extensions-seg.test-d.ts",
      "packages/e2e/integration/extensions-seg.test.ts",
    ],
    semantics: {
      providerAcceptance: "pending",
      publicExportAcceptance: "pending",
    },
  },
  {
    id: "operator:$extension:seg.&&($extension:seg.seg,$extension:seg.seg)",
    disposition: "query",
    reason:
      "Exact native SQL operator or routine with validated seg endpoints, native float4 results and strict-null codecs.",
    evidence: [
      "apps/loom/src/tooling/extensions/manifests/seg.json",
      "https://www.postgresql.org/docs/18/seg.html",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/seg.c",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/segparse.y",
      "apps/loom/src/core/extensions/adapters/seg.ts",
      "packages/tests/unit/extensions-seg.test.ts",
      "packages/tests/types/extensions-seg.test-d.ts",
      "packages/e2e/integration/extensions-seg.test.ts",
    ],
    semantics: {
      providerAcceptance: "pending",
      publicExportAcceptance: "pending",
    },
  },
  {
    id: "operator:$extension:seg.&<($extension:seg.seg,$extension:seg.seg)",
    disposition: "query",
    reason:
      "Exact native SQL operator or routine with validated seg endpoints, native float4 results and strict-null codecs.",
    evidence: [
      "apps/loom/src/tooling/extensions/manifests/seg.json",
      "https://www.postgresql.org/docs/18/seg.html",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/seg.c",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/segparse.y",
      "apps/loom/src/core/extensions/adapters/seg.ts",
      "packages/tests/unit/extensions-seg.test.ts",
      "packages/tests/types/extensions-seg.test-d.ts",
      "packages/e2e/integration/extensions-seg.test.ts",
    ],
    semantics: {
      providerAcceptance: "pending",
      publicExportAcceptance: "pending",
    },
  },
  {
    id: "operator:$extension:seg.&>($extension:seg.seg,$extension:seg.seg)",
    disposition: "query",
    reason:
      "Exact native SQL operator or routine with validated seg endpoints, native float4 results and strict-null codecs.",
    evidence: [
      "apps/loom/src/tooling/extensions/manifests/seg.json",
      "https://www.postgresql.org/docs/18/seg.html",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/seg.c",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/segparse.y",
      "apps/loom/src/core/extensions/adapters/seg.ts",
      "packages/tests/unit/extensions-seg.test.ts",
      "packages/tests/types/extensions-seg.test-d.ts",
      "packages/e2e/integration/extensions-seg.test.ts",
    ],
    semantics: {
      providerAcceptance: "pending",
      publicExportAcceptance: "pending",
    },
  },
  {
    id: "operator:$extension:seg.<($extension:seg.seg,$extension:seg.seg)",
    disposition: "query",
    reason:
      "Exact native SQL operator or routine with validated seg endpoints, native float4 results and strict-null codecs.",
    evidence: [
      "apps/loom/src/tooling/extensions/manifests/seg.json",
      "https://www.postgresql.org/docs/18/seg.html",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/seg.c",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/segparse.y",
      "apps/loom/src/core/extensions/adapters/seg.ts",
      "packages/tests/unit/extensions-seg.test.ts",
      "packages/tests/types/extensions-seg.test-d.ts",
      "packages/e2e/integration/extensions-seg.test.ts",
    ],
    semantics: {
      providerAcceptance: "pending",
      publicExportAcceptance: "pending",
    },
  },
  {
    id: "operator:$extension:seg.<@($extension:seg.seg,$extension:seg.seg)",
    disposition: "query",
    reason:
      "Exact native SQL operator or routine with validated seg endpoints, native float4 results and strict-null codecs.",
    evidence: [
      "apps/loom/src/tooling/extensions/manifests/seg.json",
      "https://www.postgresql.org/docs/18/seg.html",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/seg.c",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/segparse.y",
      "apps/loom/src/core/extensions/adapters/seg.ts",
      "packages/tests/unit/extensions-seg.test.ts",
      "packages/tests/types/extensions-seg.test-d.ts",
      "packages/e2e/integration/extensions-seg.test.ts",
    ],
    semantics: {
      providerAcceptance: "pending",
      publicExportAcceptance: "pending",
    },
  },
  {
    id: "operator:$extension:seg.<<($extension:seg.seg,$extension:seg.seg)",
    disposition: "query",
    reason:
      "Exact native SQL operator or routine with validated seg endpoints, native float4 results and strict-null codecs.",
    evidence: [
      "apps/loom/src/tooling/extensions/manifests/seg.json",
      "https://www.postgresql.org/docs/18/seg.html",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/seg.c",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/segparse.y",
      "apps/loom/src/core/extensions/adapters/seg.ts",
      "packages/tests/unit/extensions-seg.test.ts",
      "packages/tests/types/extensions-seg.test-d.ts",
      "packages/e2e/integration/extensions-seg.test.ts",
    ],
    semantics: {
      providerAcceptance: "pending",
      publicExportAcceptance: "pending",
    },
  },
  {
    id: "operator:$extension:seg.<=($extension:seg.seg,$extension:seg.seg)",
    disposition: "query",
    reason:
      "Exact native SQL operator or routine with validated seg endpoints, native float4 results and strict-null codecs.",
    evidence: [
      "apps/loom/src/tooling/extensions/manifests/seg.json",
      "https://www.postgresql.org/docs/18/seg.html",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/seg.c",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/segparse.y",
      "apps/loom/src/core/extensions/adapters/seg.ts",
      "packages/tests/unit/extensions-seg.test.ts",
      "packages/tests/types/extensions-seg.test-d.ts",
      "packages/e2e/integration/extensions-seg.test.ts",
    ],
    semantics: {
      providerAcceptance: "pending",
      publicExportAcceptance: "pending",
    },
  },
  {
    id: "operator:$extension:seg.<>($extension:seg.seg,$extension:seg.seg)",
    disposition: "query",
    reason:
      "Exact native SQL operator or routine with validated seg endpoints, native float4 results and strict-null codecs.",
    evidence: [
      "apps/loom/src/tooling/extensions/manifests/seg.json",
      "https://www.postgresql.org/docs/18/seg.html",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/seg.c",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/segparse.y",
      "apps/loom/src/core/extensions/adapters/seg.ts",
      "packages/tests/unit/extensions-seg.test.ts",
      "packages/tests/types/extensions-seg.test-d.ts",
      "packages/e2e/integration/extensions-seg.test.ts",
    ],
    semantics: {
      providerAcceptance: "pending",
      publicExportAcceptance: "pending",
    },
  },
  {
    id: "operator:$extension:seg.=($extension:seg.seg,$extension:seg.seg)",
    disposition: "query",
    reason:
      "Exact native SQL operator or routine with validated seg endpoints, native float4 results and strict-null codecs.",
    evidence: [
      "apps/loom/src/tooling/extensions/manifests/seg.json",
      "https://www.postgresql.org/docs/18/seg.html",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/seg.c",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/segparse.y",
      "apps/loom/src/core/extensions/adapters/seg.ts",
      "packages/tests/unit/extensions-seg.test.ts",
      "packages/tests/types/extensions-seg.test-d.ts",
      "packages/e2e/integration/extensions-seg.test.ts",
    ],
    semantics: {
      providerAcceptance: "pending",
      publicExportAcceptance: "pending",
    },
  },
  {
    id: "operator:$extension:seg.>($extension:seg.seg,$extension:seg.seg)",
    disposition: "query",
    reason:
      "Exact native SQL operator or routine with validated seg endpoints, native float4 results and strict-null codecs.",
    evidence: [
      "apps/loom/src/tooling/extensions/manifests/seg.json",
      "https://www.postgresql.org/docs/18/seg.html",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/seg.c",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/segparse.y",
      "apps/loom/src/core/extensions/adapters/seg.ts",
      "packages/tests/unit/extensions-seg.test.ts",
      "packages/tests/types/extensions-seg.test-d.ts",
      "packages/e2e/integration/extensions-seg.test.ts",
    ],
    semantics: {
      providerAcceptance: "pending",
      publicExportAcceptance: "pending",
    },
  },
  {
    id: "operator:$extension:seg.>=($extension:seg.seg,$extension:seg.seg)",
    disposition: "query",
    reason:
      "Exact native SQL operator or routine with validated seg endpoints, native float4 results and strict-null codecs.",
    evidence: [
      "apps/loom/src/tooling/extensions/manifests/seg.json",
      "https://www.postgresql.org/docs/18/seg.html",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/seg.c",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/segparse.y",
      "apps/loom/src/core/extensions/adapters/seg.ts",
      "packages/tests/unit/extensions-seg.test.ts",
      "packages/tests/types/extensions-seg.test-d.ts",
      "packages/e2e/integration/extensions-seg.test.ts",
    ],
    semantics: {
      providerAcceptance: "pending",
      publicExportAcceptance: "pending",
    },
  },
  {
    id: "operator:$extension:seg.>>($extension:seg.seg,$extension:seg.seg)",
    disposition: "query",
    reason:
      "Exact native SQL operator or routine with validated seg endpoints, native float4 results and strict-null codecs.",
    evidence: [
      "apps/loom/src/tooling/extensions/manifests/seg.json",
      "https://www.postgresql.org/docs/18/seg.html",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/seg.c",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/segparse.y",
      "apps/loom/src/core/extensions/adapters/seg.ts",
      "packages/tests/unit/extensions-seg.test.ts",
      "packages/tests/types/extensions-seg.test-d.ts",
      "packages/e2e/integration/extensions-seg.test.ts",
    ],
    semantics: {
      providerAcceptance: "pending",
      publicExportAcceptance: "pending",
    },
  },
  {
    id: "opfamily:$extension:seg.gist_seg_ops/gist",
    disposition: "internal",
    reason:
      "Backend callback or access-method catalog wiring; exercised only through the owning native type or index path.",
    evidence: [
      "apps/loom/src/tooling/extensions/manifests/seg.json",
      "https://www.postgresql.org/docs/18/seg.html",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/seg.c",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/segparse.y",
      "apps/loom/src/core/extensions/adapters/seg.ts",
      "packages/tests/unit/extensions-seg.test.ts",
      "packages/tests/types/extensions-seg.test-d.ts",
      "packages/e2e/integration/extensions-seg.test.ts",
    ],
    semantics: {
      providerAcceptance: "pending",
      publicExportAcceptance: "pending",
      parent: "opclass:$extension:seg.gist_seg_ops/gist",
    },
  },
  {
    id: "opfamily:$extension:seg.seg_ops/btree",
    disposition: "internal",
    reason:
      "Backend callback or access-method catalog wiring; exercised only through the owning native type or index path.",
    evidence: [
      "apps/loom/src/tooling/extensions/manifests/seg.json",
      "https://www.postgresql.org/docs/18/seg.html",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/seg.c",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/segparse.y",
      "apps/loom/src/core/extensions/adapters/seg.ts",
      "packages/tests/unit/extensions-seg.test.ts",
      "packages/tests/types/extensions-seg.test-d.ts",
      "packages/e2e/integration/extensions-seg.test.ts",
    ],
    semantics: {
      providerAcceptance: "pending",
      publicExportAcceptance: "pending",
      parent: "opclass:$extension:seg.seg_ops/btree",
    },
  },
  {
    id: "routine:$extension:seg.gseg_consistent(pg_catalog.internal,$extension:seg.seg,pg_catalog.int2,pg_catalog.oid,pg_catalog.internal)",
    disposition: "internal",
    reason:
      "Backend callback or access-method catalog wiring; exercised only through the owning native type or index path.",
    evidence: [
      "apps/loom/src/tooling/extensions/manifests/seg.json",
      "https://www.postgresql.org/docs/18/seg.html",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/seg.c",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/segparse.y",
      "apps/loom/src/core/extensions/adapters/seg.ts",
      "packages/tests/unit/extensions-seg.test.ts",
      "packages/tests/types/extensions-seg.test-d.ts",
      "packages/e2e/integration/extensions-seg.test.ts",
    ],
    semantics: {
      providerAcceptance: "pending",
      publicExportAcceptance: "pending",
      parent: "opclass:$extension:seg.gist_seg_ops/gist",
    },
  },
  {
    id: "routine:$extension:seg.gseg_penalty(pg_catalog.internal,pg_catalog.internal,pg_catalog.internal)",
    disposition: "internal",
    reason:
      "Backend callback or access-method catalog wiring; exercised only through the owning native type or index path.",
    evidence: [
      "apps/loom/src/tooling/extensions/manifests/seg.json",
      "https://www.postgresql.org/docs/18/seg.html",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/seg.c",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/segparse.y",
      "apps/loom/src/core/extensions/adapters/seg.ts",
      "packages/tests/unit/extensions-seg.test.ts",
      "packages/tests/types/extensions-seg.test-d.ts",
      "packages/e2e/integration/extensions-seg.test.ts",
    ],
    semantics: {
      providerAcceptance: "pending",
      publicExportAcceptance: "pending",
      parent: "opclass:$extension:seg.gist_seg_ops/gist",
    },
  },
  {
    id: "routine:$extension:seg.gseg_picksplit(pg_catalog.internal,pg_catalog.internal)",
    disposition: "internal",
    reason:
      "Backend callback or access-method catalog wiring; exercised only through the owning native type or index path.",
    evidence: [
      "apps/loom/src/tooling/extensions/manifests/seg.json",
      "https://www.postgresql.org/docs/18/seg.html",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/seg.c",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/segparse.y",
      "apps/loom/src/core/extensions/adapters/seg.ts",
      "packages/tests/unit/extensions-seg.test.ts",
      "packages/tests/types/extensions-seg.test-d.ts",
      "packages/e2e/integration/extensions-seg.test.ts",
    ],
    semantics: {
      providerAcceptance: "pending",
      publicExportAcceptance: "pending",
      parent: "opclass:$extension:seg.gist_seg_ops/gist",
    },
  },
  {
    id: "routine:$extension:seg.gseg_same($extension:seg.seg,$extension:seg.seg,pg_catalog.internal)",
    disposition: "internal",
    reason:
      "Backend callback or access-method catalog wiring; exercised only through the owning native type or index path.",
    evidence: [
      "apps/loom/src/tooling/extensions/manifests/seg.json",
      "https://www.postgresql.org/docs/18/seg.html",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/seg.c",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/segparse.y",
      "apps/loom/src/core/extensions/adapters/seg.ts",
      "packages/tests/unit/extensions-seg.test.ts",
      "packages/tests/types/extensions-seg.test-d.ts",
      "packages/e2e/integration/extensions-seg.test.ts",
    ],
    semantics: {
      providerAcceptance: "pending",
      publicExportAcceptance: "pending",
      parent: "opclass:$extension:seg.gist_seg_ops/gist",
    },
  },
  {
    id: "routine:$extension:seg.gseg_union(pg_catalog.internal,pg_catalog.internal)",
    disposition: "internal",
    reason:
      "Backend callback or access-method catalog wiring; exercised only through the owning native type or index path.",
    evidence: [
      "apps/loom/src/tooling/extensions/manifests/seg.json",
      "https://www.postgresql.org/docs/18/seg.html",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/seg.c",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/segparse.y",
      "apps/loom/src/core/extensions/adapters/seg.ts",
      "packages/tests/unit/extensions-seg.test.ts",
      "packages/tests/types/extensions-seg.test-d.ts",
      "packages/e2e/integration/extensions-seg.test.ts",
    ],
    semantics: {
      providerAcceptance: "pending",
      publicExportAcceptance: "pending",
      parent: "opclass:$extension:seg.gist_seg_ops/gist",
    },
  },
  {
    id: "routine:$extension:seg.seg_center($extension:seg.seg)",
    disposition: "query",
    reason:
      "Exact native SQL operator or routine with validated seg endpoints, native float4 results and strict-null codecs.",
    evidence: [
      "apps/loom/src/tooling/extensions/manifests/seg.json",
      "https://www.postgresql.org/docs/18/seg.html",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/seg.c",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/segparse.y",
      "apps/loom/src/core/extensions/adapters/seg.ts",
      "packages/tests/unit/extensions-seg.test.ts",
      "packages/tests/types/extensions-seg.test-d.ts",
      "packages/e2e/integration/extensions-seg.test.ts",
    ],
    semantics: {
      providerAcceptance: "pending",
      publicExportAcceptance: "pending",
    },
  },
  {
    id: "routine:$extension:seg.seg_cmp($extension:seg.seg,$extension:seg.seg)",
    disposition: "query",
    reason:
      "Exact native SQL operator or routine with validated seg endpoints, native float4 results and strict-null codecs.",
    evidence: [
      "apps/loom/src/tooling/extensions/manifests/seg.json",
      "https://www.postgresql.org/docs/18/seg.html",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/seg.c",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/segparse.y",
      "apps/loom/src/core/extensions/adapters/seg.ts",
      "packages/tests/unit/extensions-seg.test.ts",
      "packages/tests/types/extensions-seg.test-d.ts",
      "packages/e2e/integration/extensions-seg.test.ts",
    ],
    semantics: {
      providerAcceptance: "pending",
      publicExportAcceptance: "pending",
    },
  },
  {
    id: "routine:$extension:seg.seg_contained($extension:seg.seg,$extension:seg.seg)",
    disposition: "query",
    reason:
      "Exact native SQL operator or routine with validated seg endpoints, native float4 results and strict-null codecs.",
    evidence: [
      "apps/loom/src/tooling/extensions/manifests/seg.json",
      "https://www.postgresql.org/docs/18/seg.html",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/seg.c",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/segparse.y",
      "apps/loom/src/core/extensions/adapters/seg.ts",
      "packages/tests/unit/extensions-seg.test.ts",
      "packages/tests/types/extensions-seg.test-d.ts",
      "packages/e2e/integration/extensions-seg.test.ts",
    ],
    semantics: {
      providerAcceptance: "pending",
      publicExportAcceptance: "pending",
    },
  },
  {
    id: "routine:$extension:seg.seg_contains($extension:seg.seg,$extension:seg.seg)",
    disposition: "query",
    reason:
      "Exact native SQL operator or routine with validated seg endpoints, native float4 results and strict-null codecs.",
    evidence: [
      "apps/loom/src/tooling/extensions/manifests/seg.json",
      "https://www.postgresql.org/docs/18/seg.html",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/seg.c",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/segparse.y",
      "apps/loom/src/core/extensions/adapters/seg.ts",
      "packages/tests/unit/extensions-seg.test.ts",
      "packages/tests/types/extensions-seg.test-d.ts",
      "packages/e2e/integration/extensions-seg.test.ts",
    ],
    semantics: {
      providerAcceptance: "pending",
      publicExportAcceptance: "pending",
    },
  },
  {
    id: "routine:$extension:seg.seg_different($extension:seg.seg,$extension:seg.seg)",
    disposition: "query",
    reason:
      "Exact native SQL operator or routine with validated seg endpoints, native float4 results and strict-null codecs.",
    evidence: [
      "apps/loom/src/tooling/extensions/manifests/seg.json",
      "https://www.postgresql.org/docs/18/seg.html",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/seg.c",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/segparse.y",
      "apps/loom/src/core/extensions/adapters/seg.ts",
      "packages/tests/unit/extensions-seg.test.ts",
      "packages/tests/types/extensions-seg.test-d.ts",
      "packages/e2e/integration/extensions-seg.test.ts",
    ],
    semantics: {
      providerAcceptance: "pending",
      publicExportAcceptance: "pending",
    },
  },
  {
    id: "routine:$extension:seg.seg_ge($extension:seg.seg,$extension:seg.seg)",
    disposition: "query",
    reason:
      "Exact native SQL operator or routine with validated seg endpoints, native float4 results and strict-null codecs.",
    evidence: [
      "apps/loom/src/tooling/extensions/manifests/seg.json",
      "https://www.postgresql.org/docs/18/seg.html",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/seg.c",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/segparse.y",
      "apps/loom/src/core/extensions/adapters/seg.ts",
      "packages/tests/unit/extensions-seg.test.ts",
      "packages/tests/types/extensions-seg.test-d.ts",
      "packages/e2e/integration/extensions-seg.test.ts",
    ],
    semantics: {
      providerAcceptance: "pending",
      publicExportAcceptance: "pending",
    },
  },
  {
    id: "routine:$extension:seg.seg_gt($extension:seg.seg,$extension:seg.seg)",
    disposition: "query",
    reason:
      "Exact native SQL operator or routine with validated seg endpoints, native float4 results and strict-null codecs.",
    evidence: [
      "apps/loom/src/tooling/extensions/manifests/seg.json",
      "https://www.postgresql.org/docs/18/seg.html",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/seg.c",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/segparse.y",
      "apps/loom/src/core/extensions/adapters/seg.ts",
      "packages/tests/unit/extensions-seg.test.ts",
      "packages/tests/types/extensions-seg.test-d.ts",
      "packages/e2e/integration/extensions-seg.test.ts",
    ],
    semantics: {
      providerAcceptance: "pending",
      publicExportAcceptance: "pending",
    },
  },
  {
    id: "routine:$extension:seg.seg_in(pg_catalog.cstring)",
    disposition: "internal",
    reason:
      "Backend callback or access-method catalog wiring; exercised only through the owning native type or index path.",
    evidence: [
      "apps/loom/src/tooling/extensions/manifests/seg.json",
      "https://www.postgresql.org/docs/18/seg.html",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/seg.c",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/segparse.y",
      "apps/loom/src/core/extensions/adapters/seg.ts",
      "packages/tests/unit/extensions-seg.test.ts",
      "packages/tests/types/extensions-seg.test-d.ts",
      "packages/e2e/integration/extensions-seg.test.ts",
    ],
    semantics: {
      providerAcceptance: "pending",
      publicExportAcceptance: "pending",
      parent: "type:$extension:seg.seg",
    },
  },
  {
    id: "routine:$extension:seg.seg_inter($extension:seg.seg,$extension:seg.seg)",
    disposition: "query",
    reason:
      "Exact native SQL operator or routine with validated seg endpoints, native float4 results and strict-null codecs.",
    evidence: [
      "apps/loom/src/tooling/extensions/manifests/seg.json",
      "https://www.postgresql.org/docs/18/seg.html",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/seg.c",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/segparse.y",
      "apps/loom/src/core/extensions/adapters/seg.ts",
      "packages/tests/unit/extensions-seg.test.ts",
      "packages/tests/types/extensions-seg.test-d.ts",
      "packages/e2e/integration/extensions-seg.test.ts",
    ],
    semantics: {
      providerAcceptance: "pending",
      publicExportAcceptance: "pending",
    },
  },
  {
    id: "routine:$extension:seg.seg_le($extension:seg.seg,$extension:seg.seg)",
    disposition: "query",
    reason:
      "Exact native SQL operator or routine with validated seg endpoints, native float4 results and strict-null codecs.",
    evidence: [
      "apps/loom/src/tooling/extensions/manifests/seg.json",
      "https://www.postgresql.org/docs/18/seg.html",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/seg.c",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/segparse.y",
      "apps/loom/src/core/extensions/adapters/seg.ts",
      "packages/tests/unit/extensions-seg.test.ts",
      "packages/tests/types/extensions-seg.test-d.ts",
      "packages/e2e/integration/extensions-seg.test.ts",
    ],
    semantics: {
      providerAcceptance: "pending",
      publicExportAcceptance: "pending",
    },
  },
  {
    id: "routine:$extension:seg.seg_left($extension:seg.seg,$extension:seg.seg)",
    disposition: "query",
    reason:
      "Exact native SQL operator or routine with validated seg endpoints, native float4 results and strict-null codecs.",
    evidence: [
      "apps/loom/src/tooling/extensions/manifests/seg.json",
      "https://www.postgresql.org/docs/18/seg.html",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/seg.c",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/segparse.y",
      "apps/loom/src/core/extensions/adapters/seg.ts",
      "packages/tests/unit/extensions-seg.test.ts",
      "packages/tests/types/extensions-seg.test-d.ts",
      "packages/e2e/integration/extensions-seg.test.ts",
    ],
    semantics: {
      providerAcceptance: "pending",
      publicExportAcceptance: "pending",
    },
  },
  {
    id: "routine:$extension:seg.seg_lower($extension:seg.seg)",
    disposition: "query",
    reason:
      "Exact native SQL operator or routine with validated seg endpoints, native float4 results and strict-null codecs.",
    evidence: [
      "apps/loom/src/tooling/extensions/manifests/seg.json",
      "https://www.postgresql.org/docs/18/seg.html",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/seg.c",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/segparse.y",
      "apps/loom/src/core/extensions/adapters/seg.ts",
      "packages/tests/unit/extensions-seg.test.ts",
      "packages/tests/types/extensions-seg.test-d.ts",
      "packages/e2e/integration/extensions-seg.test.ts",
    ],
    semantics: {
      providerAcceptance: "pending",
      publicExportAcceptance: "pending",
    },
  },
  {
    id: "routine:$extension:seg.seg_lt($extension:seg.seg,$extension:seg.seg)",
    disposition: "query",
    reason:
      "Exact native SQL operator or routine with validated seg endpoints, native float4 results and strict-null codecs.",
    evidence: [
      "apps/loom/src/tooling/extensions/manifests/seg.json",
      "https://www.postgresql.org/docs/18/seg.html",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/seg.c",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/segparse.y",
      "apps/loom/src/core/extensions/adapters/seg.ts",
      "packages/tests/unit/extensions-seg.test.ts",
      "packages/tests/types/extensions-seg.test-d.ts",
      "packages/e2e/integration/extensions-seg.test.ts",
    ],
    semantics: {
      providerAcceptance: "pending",
      publicExportAcceptance: "pending",
    },
  },
  {
    id: "routine:$extension:seg.seg_out($extension:seg.seg)",
    disposition: "internal",
    reason:
      "Backend callback or access-method catalog wiring; exercised only through the owning native type or index path.",
    evidence: [
      "apps/loom/src/tooling/extensions/manifests/seg.json",
      "https://www.postgresql.org/docs/18/seg.html",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/seg.c",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/segparse.y",
      "apps/loom/src/core/extensions/adapters/seg.ts",
      "packages/tests/unit/extensions-seg.test.ts",
      "packages/tests/types/extensions-seg.test-d.ts",
      "packages/e2e/integration/extensions-seg.test.ts",
    ],
    semantics: {
      providerAcceptance: "pending",
      publicExportAcceptance: "pending",
      parent: "type:$extension:seg.seg",
    },
  },
  {
    id: "routine:$extension:seg.seg_over_left($extension:seg.seg,$extension:seg.seg)",
    disposition: "query",
    reason:
      "Exact native SQL operator or routine with validated seg endpoints, native float4 results and strict-null codecs.",
    evidence: [
      "apps/loom/src/tooling/extensions/manifests/seg.json",
      "https://www.postgresql.org/docs/18/seg.html",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/seg.c",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/segparse.y",
      "apps/loom/src/core/extensions/adapters/seg.ts",
      "packages/tests/unit/extensions-seg.test.ts",
      "packages/tests/types/extensions-seg.test-d.ts",
      "packages/e2e/integration/extensions-seg.test.ts",
    ],
    semantics: {
      providerAcceptance: "pending",
      publicExportAcceptance: "pending",
    },
  },
  {
    id: "routine:$extension:seg.seg_over_right($extension:seg.seg,$extension:seg.seg)",
    disposition: "query",
    reason:
      "Exact native SQL operator or routine with validated seg endpoints, native float4 results and strict-null codecs.",
    evidence: [
      "apps/loom/src/tooling/extensions/manifests/seg.json",
      "https://www.postgresql.org/docs/18/seg.html",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/seg.c",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/segparse.y",
      "apps/loom/src/core/extensions/adapters/seg.ts",
      "packages/tests/unit/extensions-seg.test.ts",
      "packages/tests/types/extensions-seg.test-d.ts",
      "packages/e2e/integration/extensions-seg.test.ts",
    ],
    semantics: {
      providerAcceptance: "pending",
      publicExportAcceptance: "pending",
    },
  },
  {
    id: "routine:$extension:seg.seg_overlap($extension:seg.seg,$extension:seg.seg)",
    disposition: "query",
    reason:
      "Exact native SQL operator or routine with validated seg endpoints, native float4 results and strict-null codecs.",
    evidence: [
      "apps/loom/src/tooling/extensions/manifests/seg.json",
      "https://www.postgresql.org/docs/18/seg.html",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/seg.c",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/segparse.y",
      "apps/loom/src/core/extensions/adapters/seg.ts",
      "packages/tests/unit/extensions-seg.test.ts",
      "packages/tests/types/extensions-seg.test-d.ts",
      "packages/e2e/integration/extensions-seg.test.ts",
    ],
    semantics: {
      providerAcceptance: "pending",
      publicExportAcceptance: "pending",
    },
  },
  {
    id: "routine:$extension:seg.seg_right($extension:seg.seg,$extension:seg.seg)",
    disposition: "query",
    reason:
      "Exact native SQL operator or routine with validated seg endpoints, native float4 results and strict-null codecs.",
    evidence: [
      "apps/loom/src/tooling/extensions/manifests/seg.json",
      "https://www.postgresql.org/docs/18/seg.html",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/seg.c",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/segparse.y",
      "apps/loom/src/core/extensions/adapters/seg.ts",
      "packages/tests/unit/extensions-seg.test.ts",
      "packages/tests/types/extensions-seg.test-d.ts",
      "packages/e2e/integration/extensions-seg.test.ts",
    ],
    semantics: {
      providerAcceptance: "pending",
      publicExportAcceptance: "pending",
    },
  },
  {
    id: "routine:$extension:seg.seg_same($extension:seg.seg,$extension:seg.seg)",
    disposition: "query",
    reason:
      "Exact native SQL operator or routine with validated seg endpoints, native float4 results and strict-null codecs.",
    evidence: [
      "apps/loom/src/tooling/extensions/manifests/seg.json",
      "https://www.postgresql.org/docs/18/seg.html",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/seg.c",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/segparse.y",
      "apps/loom/src/core/extensions/adapters/seg.ts",
      "packages/tests/unit/extensions-seg.test.ts",
      "packages/tests/types/extensions-seg.test-d.ts",
      "packages/e2e/integration/extensions-seg.test.ts",
    ],
    semantics: {
      providerAcceptance: "pending",
      publicExportAcceptance: "pending",
    },
  },
  {
    id: "routine:$extension:seg.seg_size($extension:seg.seg)",
    disposition: "query",
    reason:
      "Exact native SQL operator or routine with validated seg endpoints, native float4 results and strict-null codecs.",
    evidence: [
      "apps/loom/src/tooling/extensions/manifests/seg.json",
      "https://www.postgresql.org/docs/18/seg.html",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/seg.c",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/segparse.y",
      "apps/loom/src/core/extensions/adapters/seg.ts",
      "packages/tests/unit/extensions-seg.test.ts",
      "packages/tests/types/extensions-seg.test-d.ts",
      "packages/e2e/integration/extensions-seg.test.ts",
    ],
    semantics: {
      providerAcceptance: "pending",
      publicExportAcceptance: "pending",
    },
  },
  {
    id: "routine:$extension:seg.seg_union($extension:seg.seg,$extension:seg.seg)",
    disposition: "query",
    reason:
      "Exact native SQL operator or routine with validated seg endpoints, native float4 results and strict-null codecs.",
    evidence: [
      "apps/loom/src/tooling/extensions/manifests/seg.json",
      "https://www.postgresql.org/docs/18/seg.html",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/seg.c",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/segparse.y",
      "apps/loom/src/core/extensions/adapters/seg.ts",
      "packages/tests/unit/extensions-seg.test.ts",
      "packages/tests/types/extensions-seg.test-d.ts",
      "packages/e2e/integration/extensions-seg.test.ts",
    ],
    semantics: {
      providerAcceptance: "pending",
      publicExportAcceptance: "pending",
    },
  },
  {
    id: "routine:$extension:seg.seg_upper($extension:seg.seg)",
    disposition: "query",
    reason:
      "Exact native SQL operator or routine with validated seg endpoints, native float4 results and strict-null codecs.",
    evidence: [
      "apps/loom/src/tooling/extensions/manifests/seg.json",
      "https://www.postgresql.org/docs/18/seg.html",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/seg.c",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/segparse.y",
      "apps/loom/src/core/extensions/adapters/seg.ts",
      "packages/tests/unit/extensions-seg.test.ts",
      "packages/tests/types/extensions-seg.test-d.ts",
      "packages/e2e/integration/extensions-seg.test.ts",
    ],
    semantics: {
      providerAcceptance: "pending",
      publicExportAcceptance: "pending",
    },
  },
  {
    id: "type:$extension:seg._seg",
    disposition: "schema",
    reason:
      "Native seg type, dimensional array or qualified index operator class; decimal endpoint spelling retains precision and certainty.",
    evidence: [
      "apps/loom/src/tooling/extensions/manifests/seg.json",
      "https://www.postgresql.org/docs/18/seg.html",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/seg.c",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/segparse.y",
      "apps/loom/src/core/extensions/adapters/seg.ts",
      "packages/tests/unit/extensions-seg.test.ts",
      "packages/tests/types/extensions-seg.test-d.ts",
      "packages/e2e/integration/extensions-seg.test.ts",
    ],
    semantics: {
      providerAcceptance: "pending",
      publicExportAcceptance: "pending",
    },
  },
  {
    id: "type:$extension:seg.seg",
    disposition: "schema",
    reason:
      "Native seg type, dimensional array or qualified index operator class; decimal endpoint spelling retains precision and certainty.",
    evidence: [
      "apps/loom/src/tooling/extensions/manifests/seg.json",
      "https://www.postgresql.org/docs/18/seg.html",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/seg.c",
      "https://github.com/postgres/postgres/blob/REL_18_STABLE/contrib/seg/segparse.y",
      "apps/loom/src/core/extensions/adapters/seg.ts",
      "packages/tests/unit/extensions-seg.test.ts",
      "packages/tests/types/extensions-seg.test-d.ts",
      "packages/e2e/integration/extensions-seg.test.ts",
    ],
    semantics: {
      providerAcceptance: "pending",
      publicExportAcceptance: "pending",
    },
  },
] as const;
