"""Materialize only PostGIS-owned captured queryable relations."""
import json,pathlib
root=pathlib.Path(__file__).resolve().parents[3];p=root/'apps/loom/src/core/extensions/adapters/postgis.ts';s=p.read_text();m=json.loads((root/'apps/loom/src/tooling/extensions/manifests/postgis.json').read_text())['contract']['members'];q=lambda x:json.dumps(x,ensure_ascii=False)
codec={'int4':'c19','varchar':'c21','name':'c29','text':'c14'};rowcodecs={'geography_columns':'c38','geometry_columns':'c39','spatial_ref_sys':'c41'};lines=[];views=[];tables=[]
for x in m:
 if x['kind']!='relation' or x['relationKind'] not in ['v','r']:continue
 fields='{'+','.join(q(a['name'])+':'+('n' if a['nullable'] else '')+codec[a['type']['name']] for a in x['columns'])+'} as const';name=x['name'];var=name+'Columns';lines.append('const '+var+'='+fields+';');selection=', '.join(a['name'] for a in x['columns']);lines.append(f'const {name}=(alias:string)=>extensionRows(checkedExtensionExpression(sql`(select ${{sql.join(Object.keys({var}).map(name=>sql.identifier(name)),sql`, `)}} from ${{sql.identifier(descriptor.schema)}}.${{sql.identifier({q(name)})}})`,{rowcodecs[name]},[],undefined,{q(x["id"])},"external"),alias,{var},"named");');(views if x['relationKind']=='v' else tables).append(q(name)+':'+name)
helper='export function createPostgisRelationSurface(descriptor:Descriptor) {const {'+','.join(sorted(set(codec.values())|set('n'+c for c in codec.values())|set(rowcodecs.values())))+'}=createPostgisCodecDefinitions(descriptor.schema);\n'+'\n'.join(lines)+'\nreturn {views:{'+','.join(views)+'},tables:{'+','.join(tables)+'}} as const;}\nexport type PostgisRelationSurface=ReturnType<typeof createPostgisRelationSurface>;\n'
s=s.replace('export interface PostgisRows {',helper+'export interface PostgisRows {');s=s.replace('export interface PostgisAdapter extends PostgisSchemaSurface {','export interface PostgisAdapter extends PostgisSchemaSurface, PostgisRelationSurface {');s=s.replace('const {fields,arrayFields,triggers,indexes}=createPostgisSchemaSurface(descriptor);','const {fields,arrayFields,triggers,indexes}=createPostgisSchemaSurface(descriptor);\nconst {views,tables}=createPostgisRelationSurface(descriptor);').replace('fields,arrayFields,triggers,indexes,sql:', 'fields,arrayFields,triggers,indexes,views,tables,sql:');p.write_text(s)
