export { defineSchema } from "../schema/define-schema.js";
export { defineTable } from "../schema/table.js";
export { fields } from "../schema/fields.js";
export { systemFieldSql } from "../schema/system-fields.js";
export type { Id, JsonValue } from "../schema/fields.js";
export type { NativeTables, SchemaMetadata } from "../schema/compile.js";
export { encodeWire } from "../validation/encoding.js";
export type { TableValidators, SchemaValidators } from "../validation/types.js";
export { connectDatabase } from "./database/connection.js";
export type { DatabaseOptions, DatabaseSchema } from "./database/connection.js";
