/** Exact captured anon 2.5.1 routine identities. query=false members stay operator-only.
 * anyelement-returning overloads need a concrete operator codec and never invent a JS result type.
 */
export const anonRoutineSpecs = {
  "routine:anon.add_noise_on_datetime_column(pg_catalog.regclass,pg_catalog.text,pg_catalog.interval)": {
    name: "add_noise_on_datetime_column",
    args: ["regclass", "text", "interval"],
    result: "bool",
    set: false,
    query: false,
  },
  "routine:anon.add_noise_on_numeric_column(pg_catalog.regclass,pg_catalog.text,pg_catalog.float8)": {
    name: "add_noise_on_numeric_column",
    args: ["regclass", "text", "float8"],
    result: "bool",
    set: false,
    query: false,
  },
  "routine:anon.age(pg_catalog.timestamp,pg_catalog.timestamp)": {
    name: "age",
    args: ["timestamp", "timestamp"],
    result: "interval",
    set: false,
    query: true,
  },
  "routine:anon.age(pg_catalog.timestamp)": {
    name: "age",
    args: ["timestamp"],
    result: "interval",
    set: false,
    query: true,
  },
  "routine:anon.anonymize_column(pg_catalog.oid,pg_catalog.text,pg_catalog.text)": {
    name: "anonymize_column",
    args: ["oid", "text", "text"],
    result: "bool",
    set: false,
    query: false,
  },
  "routine:anon.anonymize_column(pg_catalog.text,pg_catalog.name,pg_catalog.text)": {
    name: "anonymize_column",
    args: ["text", "name", "text"],
    result: "bool",
    set: false,
    query: false,
  },
  "routine:anon.anonymize_column(pg_catalog.text,pg_catalog.name)": {
    name: "anonymize_column",
    args: ["text", "name"],
    result: "bool",
    set: false,
    query: false,
  },
  "routine:anon.anonymize_column(pg_catalog.text,pg_catalog.text,pg_catalog.text)": {
    name: "anonymize_column",
    args: ["text", "text", "text"],
    result: "bool",
    set: false,
    query: false,
  },
  "routine:anon.anonymize_database(pg_catalog.text)": {
    name: "anonymize_database",
    args: ["?text"],
    result: "bool",
    set: false,
    query: false,
  },
  "routine:anon.anonymize_table(pg_catalog.oid,pg_catalog.text)": {
    name: "anonymize_table",
    args: ["oid", "text"],
    result: "bool",
    set: false,
    query: false,
  },
  "routine:anon.anonymize_table(pg_catalog.regclass)": {
    name: "anonymize_table",
    args: ["regclass"],
    result: "bool",
    set: false,
    query: false,
  },
  "routine:anon.anonymize_table(pg_catalog.text,pg_catalog.text)": {
    name: "anonymize_table",
    args: ["text", "text"],
    result: "bool",
    set: false,
    query: false,
  },
  "routine:anon.anonymize_table(pg_catalog.text)": {
    name: "anonymize_table",
    args: ["text"],
    result: "bool",
    set: false,
    query: false,
  },
  "routine:anon.column_exists(pg_catalog.regclass,pg_catalog.name)": {
    name: "column_exists",
    args: ["regclass", "name"],
    result: "bool",
    set: false,
    query: false,
  },
  "routine:anon.concat(pg_catalog.text,pg_catalog.text,pg_catalog.text)": {
    name: "concat",
    args: ["text", "text", "text"],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.concat(pg_catalog.text,pg_catalog.text)": {
    name: "concat",
    args: ["text", "text"],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.date_add(pg_catalog.timestamptz,pg_catalog.interval)": {
    name: "date_add",
    args: ["timestamptz", "interval"],
    result: "timestamptz",
    set: false,
    query: true,
  },
  "routine:anon.date_part(pg_catalog.text,pg_catalog.interval)": {
    name: "date_part",
    args: ["text", "interval"],
    result: "float8",
    set: false,
    query: true,
  },
  "routine:anon.date_part(pg_catalog.text,pg_catalog.timestamp)": {
    name: "date_part",
    args: ["text", "timestamp"],
    result: "float8",
    set: false,
    query: true,
  },
  "routine:anon.date_subtract(pg_catalog.timestamptz,pg_catalog.interval)": {
    name: "date_subtract",
    args: ["timestamptz", "interval"],
    result: "timestamptz",
    set: false,
    query: true,
  },
  "routine:anon.date_trunc(pg_catalog.text,pg_catalog.interval)": {
    name: "date_trunc",
    args: ["text", "interval"],
    result: "interval",
    set: false,
    query: true,
  },
  "routine:anon.date_trunc(pg_catalog.text,pg_catalog.timestamp)": {
    name: "date_trunc",
    args: ["text", "timestamp"],
    result: "timestamp",
    set: false,
    query: true,
  },
  "routine:anon.date_trunc(pg_catalog.text,pg_catalog.timestamptz)": {
    name: "date_trunc",
    args: ["text", "timestamptz"],
    result: "timestamptz",
    set: false,
    query: true,
  },
  "routine:anon.detect(pg_catalog.text)": {
    name: "detect",
    args: ["?text"],
    result: "record",
    set: true,
    query: false,
    outs: [
      { name: "table_name", type: "regclass" },
      { name: "column_name", type: "name" },
      { name: "identifiers_category", type: "text" },
      { name: "direct", type: "bool" },
    ],
  },
  "routine:anon.digest(pg_catalog.text,pg_catalog.text,pg_catalog.text)": {
    name: "digest",
    args: ["text", "text", "text"],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.dnoise(pg_catalog.anyelement,pg_catalog.interval)": {
    name: "dnoise",
    args: ["anyelement", "interval"],
    result: "anyelement",
    set: false,
    query: false,
  },
  "routine:anon.drop_replica_trigger_for_table(pg_catalog.oid)": {
    name: "drop_replica_trigger_for_table",
    args: ["oid"],
    result: "bool",
    set: false,
    query: false,
  },
  "routine:anon.dummy_bic_locale(pg_catalog.text)": {
    name: "dummy_bic_locale",
    args: ["text"],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.dummy_bic()": { name: "dummy_bic", args: [], result: "text", set: false, query: true },
  "routine:anon.dummy_bs_adj_locale(pg_catalog.text)": {
    name: "dummy_bs_adj_locale",
    args: ["text"],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.dummy_bs_adj()": { name: "dummy_bs_adj", args: [], result: "text", set: false, query: true },
  "routine:anon.dummy_bs_locale(pg_catalog.text)": {
    name: "dummy_bs_locale",
    args: ["text"],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.dummy_bs_noun_locale(pg_catalog.text)": {
    name: "dummy_bs_noun_locale",
    args: ["text"],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.dummy_bs_noun()": { name: "dummy_bs_noun", args: [], result: "text", set: false, query: true },
  "routine:anon.dummy_bs_verb_locale(pg_catalog.text)": {
    name: "dummy_bs_verb_locale",
    args: ["text"],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.dummy_bs_verb()": { name: "dummy_bs_verb", args: [], result: "text", set: false, query: true },
  "routine:anon.dummy_bs()": { name: "dummy_bs", args: [], result: "text", set: false, query: true },
  "routine:anon.dummy_building_number_locale(pg_catalog.text)": {
    name: "dummy_building_number_locale",
    args: ["text"],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.dummy_building_number()": {
    name: "dummy_building_number",
    args: [],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.dummy_buzzword_locale(pg_catalog.text)": {
    name: "dummy_buzzword_locale",
    args: ["text"],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.dummy_buzzword_middle_locale(pg_catalog.text)": {
    name: "dummy_buzzword_middle_locale",
    args: ["text"],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.dummy_buzzword_middle()": {
    name: "dummy_buzzword_middle",
    args: [],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.dummy_buzzword_tail_locale(pg_catalog.text)": {
    name: "dummy_buzzword_tail_locale",
    args: ["text"],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.dummy_buzzword_tail()": {
    name: "dummy_buzzword_tail",
    args: [],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.dummy_buzzword()": { name: "dummy_buzzword", args: [], result: "text", set: false, query: true },
  "routine:anon.dummy_catchphrase_locale(pg_catalog.text)": {
    name: "dummy_catchphrase_locale",
    args: ["text"],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.dummy_catchphrase()": { name: "dummy_catchphrase", args: [], result: "text", set: false, query: true },
  "routine:anon.dummy_cell_number_locale(pg_catalog.text)": {
    name: "dummy_cell_number_locale",
    args: ["text"],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.dummy_cell_number()": { name: "dummy_cell_number", args: [], result: "text", set: false, query: true },
  "routine:anon.dummy_city_name_locale(pg_catalog.text)": {
    name: "dummy_city_name_locale",
    args: ["text"],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.dummy_city_name()": { name: "dummy_city_name", args: [], result: "text", set: false, query: true },
  "routine:anon.dummy_city_prefix_locale(pg_catalog.text)": {
    name: "dummy_city_prefix_locale",
    args: ["text"],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.dummy_city_prefix()": { name: "dummy_city_prefix", args: [], result: "text", set: false, query: true },
  "routine:anon.dummy_city_suffix_locale(pg_catalog.text)": {
    name: "dummy_city_suffix_locale",
    args: ["text"],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.dummy_city_suffix()": { name: "dummy_city_suffix", args: [], result: "text", set: false, query: true },
  "routine:anon.dummy_color_locale(pg_catalog.text)": {
    name: "dummy_color_locale",
    args: ["text"],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.dummy_color()": { name: "dummy_color", args: [], result: "text", set: false, query: true },
  "routine:anon.dummy_company_name_locale(pg_catalog.text)": {
    name: "dummy_company_name_locale",
    args: ["text"],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.dummy_company_name()": {
    name: "dummy_company_name",
    args: [],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.dummy_company_suffix_locale(pg_catalog.text)": {
    name: "dummy_company_suffix_locale",
    args: ["text"],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.dummy_company_suffix()": {
    name: "dummy_company_suffix",
    args: [],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.dummy_country_code_locale(pg_catalog.text)": {
    name: "dummy_country_code_locale",
    args: ["text"],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.dummy_country_code()": {
    name: "dummy_country_code",
    args: [],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.dummy_country_name_locale(pg_catalog.text)": {
    name: "dummy_country_name_locale",
    args: ["text"],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.dummy_country_name()": {
    name: "dummy_country_name",
    args: [],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.dummy_credit_card_number_locale(pg_catalog.text)": {
    name: "dummy_credit_card_number_locale",
    args: ["text"],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.dummy_credit_card_number()": {
    name: "dummy_credit_card_number",
    args: [],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.dummy_currency_code_locale(pg_catalog.text)": {
    name: "dummy_currency_code_locale",
    args: ["text"],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.dummy_currency_code()": {
    name: "dummy_currency_code",
    args: [],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.dummy_currency_name_locale(pg_catalog.text)": {
    name: "dummy_currency_name_locale",
    args: ["text"],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.dummy_currency_name()": {
    name: "dummy_currency_name",
    args: [],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.dummy_currency_symbol_locale(pg_catalog.text)": {
    name: "dummy_currency_symbol_locale",
    args: ["text"],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.dummy_currency_symbol()": {
    name: "dummy_currency_symbol",
    args: [],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.dummy_dir_path_locale(pg_catalog.text)": {
    name: "dummy_dir_path_locale",
    args: ["text"],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.dummy_dir_path()": { name: "dummy_dir_path", args: [], result: "text", set: false, query: true },
  "routine:anon.dummy_domain_suffix_locale(pg_catalog.text)": {
    name: "dummy_domain_suffix_locale",
    args: ["text"],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.dummy_domain_suffix()": {
    name: "dummy_domain_suffix",
    args: [],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.dummy_file_extension_locale(pg_catalog.text)": {
    name: "dummy_file_extension_locale",
    args: ["text"],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.dummy_file_extension()": {
    name: "dummy_file_extension",
    args: [],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.dummy_file_name_locale(pg_catalog.text)": {
    name: "dummy_file_name_locale",
    args: ["text"],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.dummy_file_name()": { name: "dummy_file_name", args: [], result: "text", set: false, query: true },
  "routine:anon.dummy_file_path_locale(pg_catalog.text)": {
    name: "dummy_file_path_locale",
    args: ["text"],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.dummy_file_path()": { name: "dummy_file_path", args: [], result: "text", set: false, query: true },
  "routine:anon.dummy_first_name_locale(pg_catalog.text)": {
    name: "dummy_first_name_locale",
    args: ["text"],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.dummy_first_name()": { name: "dummy_first_name", args: [], result: "text", set: false, query: true },
  "routine:anon.dummy_free_email_locale(pg_catalog.text)": {
    name: "dummy_free_email_locale",
    args: ["text"],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.dummy_free_email_provider_locale(pg_catalog.text)": {
    name: "dummy_free_email_provider_locale",
    args: ["text"],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.dummy_free_email_provider()": {
    name: "dummy_free_email_provider",
    args: [],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.dummy_free_email()": { name: "dummy_free_email", args: [], result: "text", set: false, query: true },
  "routine:anon.dummy_health_insurance_code()": {
    name: "dummy_health_insurance_code",
    args: [],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.dummy_hex_color_locale(pg_catalog.text)": {
    name: "dummy_hex_color_locale",
    args: ["text"],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.dummy_hex_color()": { name: "dummy_hex_color", args: [], result: "text", set: false, query: true },
  "routine:anon.dummy_hsl_color_locale(pg_catalog.text)": {
    name: "dummy_hsl_color_locale",
    args: ["text"],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.dummy_hsl_color()": { name: "dummy_hsl_color", args: [], result: "text", set: false, query: true },
  "routine:anon.dummy_hsla_color_locale(pg_catalog.text)": {
    name: "dummy_hsla_color_locale",
    args: ["text"],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.dummy_hsla_color()": { name: "dummy_hsla_color", args: [], result: "text", set: false, query: true },
  "routine:anon.dummy_industry_locale(pg_catalog.text)": {
    name: "dummy_industry_locale",
    args: ["text"],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.dummy_industry()": { name: "dummy_industry", args: [], result: "text", set: false, query: true },
  "routine:anon.dummy_ip_locale(pg_catalog.text)": {
    name: "dummy_ip_locale",
    args: ["text"],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.dummy_ip()": { name: "dummy_ip", args: [], result: "text", set: false, query: true },
  "routine:anon.dummy_ipv4_locale(pg_catalog.text)": {
    name: "dummy_ipv4_locale",
    args: ["text"],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.dummy_ipv4()": { name: "dummy_ipv4", args: [], result: "text", set: false, query: true },
  "routine:anon.dummy_ipv6_locale(pg_catalog.text)": {
    name: "dummy_ipv6_locale",
    args: ["text"],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.dummy_ipv6()": { name: "dummy_ipv6", args: [], result: "text", set: false, query: true },
  "routine:anon.dummy_isbn_locale(pg_catalog.text)": {
    name: "dummy_isbn_locale",
    args: ["text"],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.dummy_isbn()": { name: "dummy_isbn", args: [], result: "text", set: false, query: true },
  "routine:anon.dummy_isbn13_locale(pg_catalog.text)": {
    name: "dummy_isbn13_locale",
    args: ["text"],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.dummy_isbn13()": { name: "dummy_isbn13", args: [], result: "text", set: false, query: true },
  "routine:anon.dummy_isin_locale(pg_catalog.text)": {
    name: "dummy_isin_locale",
    args: ["text"],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.dummy_isin()": { name: "dummy_isin", args: [], result: "text", set: false, query: true },
  "routine:anon.dummy_last_name_locale(pg_catalog.text)": {
    name: "dummy_last_name_locale",
    args: ["text"],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.dummy_last_name()": { name: "dummy_last_name", args: [], result: "text", set: false, query: true },
  "routine:anon.dummy_latitude_locale(pg_catalog.text)": {
    name: "dummy_latitude_locale",
    args: ["text"],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.dummy_latitude()": { name: "dummy_latitude", args: [], result: "text", set: false, query: true },
  "routine:anon.dummy_licence_plate()": {
    name: "dummy_licence_plate",
    args: [],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.dummy_longitude_locale(pg_catalog.text)": {
    name: "dummy_longitude_locale",
    args: ["text"],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.dummy_longitude()": { name: "dummy_longitude", args: [], result: "text", set: false, query: true },
  "routine:anon.dummy_mac_address_locale(pg_catalog.text)": {
    name: "dummy_mac_address_locale",
    args: ["text"],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.dummy_mac_address()": { name: "dummy_mac_address", args: [], result: "text", set: false, query: true },
  "routine:anon.dummy_name_locale(pg_catalog.text)": {
    name: "dummy_name_locale",
    args: ["text"],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.dummy_name_with_title_locale(pg_catalog.text)": {
    name: "dummy_name_with_title_locale",
    args: ["text"],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.dummy_name_with_title()": {
    name: "dummy_name_with_title",
    args: [],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.dummy_name()": { name: "dummy_name", args: [], result: "text", set: false, query: true },
  "routine:anon.dummy_phone_number_locale(pg_catalog.text)": {
    name: "dummy_phone_number_locale",
    args: ["text"],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.dummy_phone_number()": {
    name: "dummy_phone_number",
    args: [],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.dummy_post_code_locale(pg_catalog.text)": {
    name: "dummy_post_code_locale",
    args: ["text"],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.dummy_post_code()": { name: "dummy_post_code", args: [], result: "text", set: false, query: true },
  "routine:anon.dummy_profession_locale(pg_catalog.text)": {
    name: "dummy_profession_locale",
    args: ["text"],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.dummy_profession()": { name: "dummy_profession", args: [], result: "text", set: false, query: true },
  "routine:anon.dummy_rfc_status_code_locale(pg_catalog.text)": {
    name: "dummy_rfc_status_code_locale",
    args: ["text"],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.dummy_rfc_status_code()": {
    name: "dummy_rfc_status_code",
    args: [],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.dummy_rgb_color_locale(pg_catalog.text)": {
    name: "dummy_rgb_color_locale",
    args: ["text"],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.dummy_rgb_color()": { name: "dummy_rgb_color", args: [], result: "text", set: false, query: true },
  "routine:anon.dummy_rgba_color_locale(pg_catalog.text)": {
    name: "dummy_rgba_color_locale",
    args: ["text"],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.dummy_rgba_color()": { name: "dummy_rgba_color", args: [], result: "text", set: false, query: true },
  "routine:anon.dummy_safe_email_locale(pg_catalog.text)": {
    name: "dummy_safe_email_locale",
    args: ["text"],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.dummy_safe_email()": { name: "dummy_safe_email", args: [], result: "text", set: false, query: true },
  "routine:anon.dummy_secondary_address_locale(pg_catalog.text)": {
    name: "dummy_secondary_address_locale",
    args: ["text"],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.dummy_secondary_address_type_locale(pg_catalog.text)": {
    name: "dummy_secondary_address_type_locale",
    args: ["text"],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.dummy_secondary_address_type()": {
    name: "dummy_secondary_address_type",
    args: [],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.dummy_secondary_address()": {
    name: "dummy_secondary_address",
    args: [],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.dummy_state_abbr_locale(pg_catalog.text)": {
    name: "dummy_state_abbr_locale",
    args: ["text"],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.dummy_state_abbr()": { name: "dummy_state_abbr", args: [], result: "text", set: false, query: true },
  "routine:anon.dummy_state_name_locale(pg_catalog.text)": {
    name: "dummy_state_name_locale",
    args: ["text"],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.dummy_state_name()": { name: "dummy_state_name", args: [], result: "text", set: false, query: true },
  "routine:anon.dummy_street_name_locale(pg_catalog.text)": {
    name: "dummy_street_name_locale",
    args: ["text"],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.dummy_street_name()": { name: "dummy_street_name", args: [], result: "text", set: false, query: true },
  "routine:anon.dummy_street_suffix_locale(pg_catalog.text)": {
    name: "dummy_street_suffix_locale",
    args: ["text"],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.dummy_street_suffix()": {
    name: "dummy_street_suffix",
    args: [],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.dummy_suffix_locale(pg_catalog.text)": {
    name: "dummy_suffix_locale",
    args: ["text"],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.dummy_suffix()": { name: "dummy_suffix", args: [], result: "text", set: false, query: true },
  "routine:anon.dummy_timezone_locale(pg_catalog.text)": {
    name: "dummy_timezone_locale",
    args: ["text"],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.dummy_timezone()": { name: "dummy_timezone", args: [], result: "text", set: false, query: true },
  "routine:anon.dummy_title_locale(pg_catalog.text)": {
    name: "dummy_title_locale",
    args: ["text"],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.dummy_title()": { name: "dummy_title", args: [], result: "text", set: false, query: true },
  "routine:anon.dummy_user_agent_locale(pg_catalog.text)": {
    name: "dummy_user_agent_locale",
    args: ["text"],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.dummy_user_agent()": { name: "dummy_user_agent", args: [], result: "text", set: false, query: true },
  "routine:anon.dummy_username_locale(pg_catalog.text)": {
    name: "dummy_username_locale",
    args: ["text"],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.dummy_username()": { name: "dummy_username", args: [], result: "text", set: false, query: true },
  "routine:anon.dummy_uuidv1()": { name: "dummy_uuidv1", args: [], result: "text", set: false, query: true },
  "routine:anon.dummy_uuidv3()": { name: "dummy_uuidv3", args: [], result: "text", set: false, query: true },
  "routine:anon.dummy_uuidv4()": { name: "dummy_uuidv4", args: [], result: "text", set: false, query: true },
  "routine:anon.dummy_uuidv5()": { name: "dummy_uuidv5", args: [], result: "text", set: false, query: true },
  "routine:anon.dummy_valid_statux_code_locale(pg_catalog.text)": {
    name: "dummy_valid_statux_code_locale",
    args: ["text"],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.dummy_valid_statux_code()": {
    name: "dummy_valid_statux_code",
    args: [],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.dummy_word_locale(pg_catalog.text)": {
    name: "dummy_word_locale",
    args: ["text"],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.dummy_word()": { name: "dummy_word", args: [], result: "text", set: false, query: true },
  "routine:anon.dummy_words_locale(pg_catalog.text,pg_catalog.int4range)": {
    name: "dummy_words_locale",
    args: ["text", "int4range"],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.dummy_words(pg_catalog.int4range)": {
    name: "dummy_words",
    args: ["int4range"],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.dummy_zip_code_locale(pg_catalog.text)": {
    name: "dummy_zip_code_locale",
    args: ["text"],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.dummy_zip_code()": { name: "dummy_zip_code", args: [], result: "text", set: false, query: true },
  "routine:anon.fake_address()": { name: "fake_address", args: [], result: "text", set: false, query: true },
  "routine:anon.fake_city()": { name: "fake_city", args: [], result: "text", set: false, query: true },
  "routine:anon.fake_company()": { name: "fake_company", args: [], result: "text", set: false, query: true },
  "routine:anon.fake_country()": { name: "fake_country", args: [], result: "text", set: false, query: true },
  "routine:anon.fake_email()": { name: "fake_email", args: [], result: "text", set: false, query: true },
  "routine:anon.fake_first_name()": { name: "fake_first_name", args: [], result: "text", set: false, query: true },
  "routine:anon.fake_iban()": { name: "fake_iban", args: [], result: "text", set: false, query: true },
  "routine:anon.fake_last_name()": { name: "fake_last_name", args: [], result: "text", set: false, query: true },
  "routine:anon.fake_postcode()": { name: "fake_postcode", args: [], result: "text", set: false, query: true },
  "routine:anon.fake_siret()": { name: "fake_siret", args: [], result: "text", set: false, query: true },
  "routine:anon.generalize_daterange(pg_catalog.date,pg_catalog.text)": {
    name: "generalize_daterange",
    args: ["date", "?text"],
    result: "daterange",
    set: false,
    query: true,
  },
  "routine:anon.generalize_int4range(pg_catalog.int4,pg_catalog.int4)": {
    name: "generalize_int4range",
    args: ["int4", "?int4"],
    result: "int4range",
    set: false,
    query: true,
  },
  "routine:anon.generalize_int8range(pg_catalog.int8,pg_catalog.int8)": {
    name: "generalize_int8range",
    args: ["int8", "?int8"],
    result: "int8range",
    set: false,
    query: true,
  },
  "routine:anon.generalize_numrange(pg_catalog.numeric,pg_catalog.int4)": {
    name: "generalize_numrange",
    args: ["numeric", "?int4"],
    result: "numrange",
    set: false,
    query: true,
  },
  "routine:anon.generalize_tsrange(pg_catalog.timestamp,pg_catalog.text)": {
    name: "generalize_tsrange",
    args: ["timestamp", "?text"],
    result: "tsrange",
    set: false,
    query: true,
  },
  "routine:anon.generalize_tstzrange(pg_catalog.timestamptz,pg_catalog.text)": {
    name: "generalize_tstzrange",
    args: ["timestamptz", "?text"],
    result: "tstzrange",
    set: false,
    query: true,
  },
  "routine:anon.get_attrdef(pg_catalog.int4,pg_catalog.int4)": {
    name: "get_attrdef",
    args: ["int4", "int4"],
    result: "text",
    set: false,
    query: false,
  },
  "routine:anon.get_function_schema(pg_catalog.text)": {
    name: "get_function_schema",
    args: ["text"],
    result: "text",
    set: false,
    query: false,
  },
  "routine:anon.get_relname(pg_catalog.text)": {
    name: "get_relname",
    args: ["text"],
    result: "text",
    set: false,
    query: false,
  },
  "routine:anon.get_schema(pg_catalog.text)": {
    name: "get_schema",
    args: ["text"],
    result: "text",
    set: false,
    query: false,
  },
  "routine:anon.get_tablesample_ratio(pg_catalog.oid)": {
    name: "get_tablesample_ratio",
    args: ["oid"],
    result: "text",
    set: false,
    query: false,
  },
  "routine:anon.hash(pg_catalog.text)": { name: "hash", args: ["text"], result: "text", set: false, query: true },
  "routine:anon.hasmask(pg_catalog.regrole,pg_catalog.text)": {
    name: "hasmask",
    args: ["regrole", "?text"],
    result: "bool",
    set: false,
    query: false,
  },
  "routine:anon.hex_to_int(pg_catalog.text)": {
    name: "hex_to_int",
    args: ["text"],
    result: "int4",
    set: false,
    query: true,
  },
  "routine:anon.image_blur(pg_catalog.bytea,pg_catalog.float4)": {
    name: "image_blur",
    args: ["bytea", "float4"],
    result: "bytea",
    set: false,
    query: true,
  },
  "routine:anon.image_blur(pg_catalog.bytea)": {
    name: "image_blur",
    args: ["bytea"],
    result: "bytea",
    set: false,
    query: true,
  },
  "routine:anon.init()": { name: "init", args: [], result: "bool", set: false, query: false },
  "routine:anon.is_initialized()": { name: "is_initialized", args: [], result: "bool", set: false, query: true },
  "routine:anon.k_anonymity(pg_catalog.regclass)": {
    name: "k_anonymity",
    args: ["regclass"],
    result: "int4",
    set: false,
    query: false,
  },
  "routine:anon.left(pg_catalog.text,pg_catalog.int4)": {
    name: "left",
    args: ["text", "int4"],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.length(pg_catalog.text)": { name: "length", args: ["text"], result: "int4", set: false, query: true },
  "routine:anon.load_csv(pg_catalog.regclass,pg_catalog.text)": {
    name: "load_csv",
    args: ["regclass", "text"],
    result: "bool",
    set: false,
    query: false,
  },
  "routine:anon.load_fake_data()": { name: "load_fake_data", args: [], result: "bool", set: false, query: false },
  "routine:anon.load()": { name: "load", args: [], result: "bool", set: false, query: false },
  "routine:anon.load(pg_catalog.text)": { name: "load", args: ["text"], result: "bool", set: false, query: false },
  "routine:anon.lorem_ipsum(pg_catalog.int4,pg_catalog.int4,pg_catalog.int4)": {
    name: "lorem_ipsum",
    args: ["?int4", "?int4", "?int4"],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.lower(pg_catalog.text)": { name: "lower", args: ["text"], result: "text", set: false, query: true },
  "routine:anon.make_date(pg_catalog.int4,pg_catalog.int4,pg_catalog.int4)": {
    name: "make_date",
    args: ["int4", "int4", "int4"],
    result: "date",
    set: false,
    query: true,
  },
  "routine:anon.make_time(pg_catalog.int4,pg_catalog.int4,pg_catalog.float8)": {
    name: "make_time",
    args: ["int4", "int4", "float8"],
    result: "time",
    set: false,
    query: true,
  },
  "routine:anon.mask_columns(pg_catalog.oid)": {
    name: "mask_columns",
    args: ["oid"],
    result: "record",
    set: true,
    query: false,
    outs: [
      { name: "attname", type: "name" },
      { name: "masking_filter", type: "text" },
      { name: "format_type", type: "text" },
    ],
  },
  "routine:anon.mask_create_view(pg_catalog.oid)": {
    name: "mask_create_view",
    args: ["oid"],
    result: "bool",
    set: false,
    query: false,
  },
  "routine:anon.mask_drop_view(pg_catalog.oid)": {
    name: "mask_drop_view",
    args: ["oid"],
    result: "bool",
    set: false,
    query: false,
  },
  "routine:anon.mask_filters(pg_catalog.oid)": {
    name: "mask_filters",
    args: ["oid"],
    result: "text",
    set: false,
    query: false,
  },
  "routine:anon.mask_role(pg_catalog.regrole)": {
    name: "mask_role",
    args: ["regrole"],
    result: "bool",
    set: false,
    query: false,
  },
  "routine:anon.mask_select(pg_catalog.oid)": {
    name: "mask_select",
    args: ["oid"],
    result: "text",
    set: false,
    query: false,
  },
  "routine:anon.mask_update()": { name: "mask_update", args: [], result: "bool", set: false, query: false },
  "routine:anon.masking_expressions_for_table(pg_catalog.oid,pg_catalog.text)": {
    name: "masking_expressions_for_table",
    args: ["oid", "text"],
    result: "text",
    set: false,
    query: false,
  },
  "routine:anon.masking_value_for_column(pg_catalog.oid,pg_catalog.int4,pg_catalog.text)": {
    name: "masking_value_for_column",
    args: ["oid", "int4", "text"],
    result: "text",
    set: false,
    query: false,
  },
  "routine:anon.md5(pg_catalog.text)": { name: "md5", args: ["text"], result: "text", set: false, query: true },
  "routine:anon.noise(pg_catalog.anyelement,pg_catalog.float8)": {
    name: "noise",
    args: ["anyelement", "float8"],
    result: "anyelement",
    set: false,
    query: false,
  },
  "routine:anon.notice_if_not_init()": {
    name: "notice_if_not_init",
    args: [],
    result: "text",
    set: false,
    query: false,
  },
  "routine:anon.now()": { name: "now", args: [], result: "timestamptz", set: false, query: true },
  "routine:anon.partial_email(pg_catalog.text)": {
    name: "partial_email",
    args: ["text"],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.partial(pg_catalog.text,pg_catalog.int4,pg_catalog.text,pg_catalog.int4)": {
    name: "partial",
    args: ["text", "int4", "text", "int4"],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.plop(pg_catalog.text)": { name: "plop", args: ["text"], result: "text", set: false, query: false },
  "routine:anon.projection_to_oid(pg_catalog.anyelement,pg_catalog.text,pg_catalog.int4)": {
    name: "projection_to_oid",
    args: ["anyelement", "text", "int4"],
    result: "int4",
    set: false,
    query: true,
  },
  "routine:anon.pseudo_city(pg_catalog.anyelement,pg_catalog.text)": {
    name: "pseudo_city",
    args: ["anyelement", "?text"],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.pseudo_company(pg_catalog.anyelement,pg_catalog.text)": {
    name: "pseudo_company",
    args: ["anyelement", "?text"],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.pseudo_country(pg_catalog.anyelement,pg_catalog.text)": {
    name: "pseudo_country",
    args: ["anyelement", "?text"],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.pseudo_email(pg_catalog.anyelement,pg_catalog.text)": {
    name: "pseudo_email",
    args: ["anyelement", "?text"],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.pseudo_first_name(pg_catalog.anyelement,pg_catalog.text)": {
    name: "pseudo_first_name",
    args: ["anyelement", "?text"],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.pseudo_iban(pg_catalog.anyelement,pg_catalog.text)": {
    name: "pseudo_iban",
    args: ["anyelement", "?text"],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.pseudo_last_name(pg_catalog.anyelement,pg_catalog.text)": {
    name: "pseudo_last_name",
    args: ["anyelement", "?text"],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.pseudo_shift(pg_catalog.int8)": {
    name: "pseudo_shift",
    args: ["int8"],
    result: "int8",
    set: false,
    query: true,
  },
  "routine:anon.pseudo_siret(pg_catalog.anyelement,pg_catalog.text)": {
    name: "pseudo_siret",
    args: ["anyelement", "?text"],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.pseudo_xor(pg_catalog.int8)": {
    name: "pseudo_xor",
    args: ["int8"],
    result: "int8",
    set: false,
    query: true,
  },
  "routine:anon.random_bigint_between(pg_catalog.int8,pg_catalog.int8)": {
    name: "random_bigint_between",
    args: ["int8", "int8"],
    result: "int8",
    set: false,
    query: true,
  },
  "routine:anon.random_date_between(pg_catalog.timestamptz,pg_catalog.timestamptz)": {
    name: "random_date_between",
    args: ["timestamptz", "timestamptz"],
    result: "timestamptz",
    set: false,
    query: true,
  },
  "routine:anon.random_date()": { name: "random_date", args: [], result: "timestamptz", set: false, query: true },
  "routine:anon.random_double_precision(pg_catalog.float8,pg_catalog.float8)": {
    name: "random_double_precision",
    args: ["float8", "float8"],
    result: "float8",
    set: false,
    query: true,
  },
  "routine:anon.random_hash(pg_catalog.text)": {
    name: "random_hash",
    args: ["text"],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.random_id_int()": { name: "random_id_int", args: [], result: "int4", set: false, query: true },
  "routine:anon.random_id_smallint()": {
    name: "random_id_smallint",
    args: [],
    result: "int2",
    set: false,
    query: true,
  },
  "routine:anon.random_id()": { name: "random_id", args: [], result: "int8", set: false, query: true },
  "routine:anon.random_in_daterange(pg_catalog.daterange)": {
    name: "random_in_daterange",
    args: ["daterange"],
    result: "date",
    set: false,
    query: true,
  },
  "routine:anon.random_in_enum(pg_catalog.anyelement)": {
    name: "random_in_enum",
    args: ["anyelement"],
    result: "anyelement",
    set: false,
    query: false,
  },
  "routine:anon.random_in_int4range(pg_catalog.int4range)": {
    name: "random_in_int4range",
    args: ["int4range"],
    result: "int4",
    set: false,
    query: true,
  },
  "routine:anon.random_in_int8range(pg_catalog.int8range)": {
    name: "random_in_int8range",
    args: ["int8range"],
    result: "int8",
    set: false,
    query: true,
  },
  "routine:anon.random_in_numrange(pg_catalog.numrange)": {
    name: "random_in_numrange",
    args: ["numrange"],
    result: "numeric",
    set: false,
    query: true,
  },
  "routine:anon.random_in_tsrange(pg_catalog.tsrange)": {
    name: "random_in_tsrange",
    args: ["tsrange"],
    result: "timestamp",
    set: false,
    query: true,
  },
  "routine:anon.random_in_tstzrange(pg_catalog.tstzrange)": {
    name: "random_in_tstzrange",
    args: ["tstzrange"],
    result: "timestamptz",
    set: false,
    query: true,
  },
  "routine:anon.random_in(pg_catalog.anyarray)": {
    name: "random_in",
    args: ["anyarray"],
    result: "anyelement",
    set: false,
    query: false,
  },
  "routine:anon.random_int_between(pg_catalog.int4,pg_catalog.int4)": {
    name: "random_int_between",
    args: ["int4", "int4"],
    result: "int4",
    set: false,
    query: true,
  },
  "routine:anon.random_number_with_format(pg_catalog.text)": {
    name: "random_number_with_format",
    args: ["text"],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.random_phone_with_format(pg_catalog.text)": {
    name: "random_phone_with_format",
    args: ["text"],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.random_phone()": { name: "random_phone", args: [], result: "text", set: false, query: true },
  "routine:anon.random_phone(pg_catalog.text)": {
    name: "random_phone",
    args: ["text"],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.random_real(pg_catalog.float4,pg_catalog.float4)": {
    name: "random_real",
    args: ["float4", "float4"],
    result: "float4",
    set: false,
    query: true,
  },
  "routine:anon.random_string(pg_catalog.int4)": {
    name: "random_string",
    args: ["int4"],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.random_string(pg_catalog.int4range)": {
    name: "random_string",
    args: ["int4range"],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.random_time()": { name: "random_time", args: [], result: "time", set: false, query: true },
  "routine:anon.random_zip()": { name: "random_zip", args: [], result: "text", set: false, query: true },
  "routine:anon.random()": { name: "random", args: [], result: "float8", set: false, query: true },
  "routine:anon.refresh_replica_masking(pg_catalog.text)": {
    name: "refresh_replica_masking",
    args: ["?text"],
    result: "bool",
    set: false,
    query: false,
  },
  "routine:anon.refresh_replica_trigger_for_table(pg_catalog.oid,pg_catalog.text)": {
    name: "refresh_replica_trigger_for_table",
    args: ["oid", "text"],
    result: "bool",
    set: false,
    query: false,
  },
  "routine:anon.regexp_replace(pg_catalog.text,pg_catalog.text,pg_catalog.text,pg_catalog.text)": {
    name: "regexp_replace",
    args: ["text", "text", "text", "text"],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.regexp_replace(pg_catalog.text,pg_catalog.text,pg_catalog.text)": {
    name: "regexp_replace",
    args: ["text", "text", "text"],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.remove_masks_for_all_columns()": {
    name: "remove_masks_for_all_columns",
    args: [],
    result: "bool",
    set: false,
    query: false,
  },
  "routine:anon.remove_masks_for_all_roles()": {
    name: "remove_masks_for_all_roles",
    args: [],
    result: "bool",
    set: false,
    query: false,
  },
  "routine:anon.replace(pg_catalog.text,pg_catalog.text,pg_catalog.text)": {
    name: "replace",
    args: ["text", "text", "text"],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.reset()": { name: "reset", args: [], result: "bool", set: false, query: false },
  "routine:anon.right(pg_catalog.text,pg_catalog.int4)": {
    name: "right",
    args: ["text", "int4"],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.set_shift(pg_catalog.int4)": {
    name: "set_shift",
    args: ["?int4"],
    result: "bool",
    set: false,
    query: false,
  },
  "routine:anon.shuffle_column(pg_catalog.regclass,pg_catalog.name,pg_catalog.name)": {
    name: "shuffle_column",
    args: ["regclass", "name", "name"],
    result: "bool",
    set: false,
    query: false,
  },
  "routine:anon.start_dynamic_masking(pg_catalog.bool)": {
    name: "start_dynamic_masking",
    args: ["?bool"],
    result: "bool",
    set: false,
    query: false,
  },
  "routine:anon.start_replica_masking(pg_catalog.text)": {
    name: "start_replica_masking",
    args: ["?text"],
    result: "bool",
    set: false,
    query: false,
  },
  "routine:anon.stop_dynamic_masking()": {
    name: "stop_dynamic_masking",
    args: [],
    result: "bool",
    set: false,
    query: false,
  },
  "routine:anon.stop_replica_masking()": {
    name: "stop_replica_masking",
    args: [],
    result: "bool",
    set: false,
    query: false,
  },
  "routine:anon.substr(pg_catalog.text,pg_catalog.int4,pg_catalog.int4)": {
    name: "substr",
    args: ["text", "int4", "int4"],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.substr(pg_catalog.text,pg_catalog.int4)": {
    name: "substr",
    args: ["text", "int4"],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.ternary(pg_catalog.bool,pg_catalog.anyelement,pg_catalog.anyelement)": {
    name: "ternary",
    args: ["bool", "anyelement", "anyelement"],
    result: "anyelement",
    set: false,
    query: false,
  },
  "routine:anon.to_char(pg_catalog.interval,pg_catalog.text)": {
    name: "to_char",
    args: ["interval", "text"],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.to_char(pg_catalog.numeric,pg_catalog.text)": {
    name: "to_char",
    args: ["numeric", "text"],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.to_char(pg_catalog.timestamp,pg_catalog.text)": {
    name: "to_char",
    args: ["timestamp", "text"],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.to_char(pg_catalog.timestamptz,pg_catalog.text)": {
    name: "to_char",
    args: ["timestamptz", "text"],
    result: "text",
    set: false,
    query: true,
  },
  "routine:anon.to_date(pg_catalog.text,pg_catalog.text)": {
    name: "to_date",
    args: ["text", "text"],
    result: "date",
    set: false,
    query: true,
  },
  "routine:anon.to_number(pg_catalog.text,pg_catalog.text)": {
    name: "to_number",
    args: ["text", "text"],
    result: "numeric",
    set: false,
    query: true,
  },
  "routine:anon.to_timestamp(pg_catalog.text,pg_catalog.text)": {
    name: "to_timestamp",
    args: ["text", "text"],
    result: "timestamptz",
    set: false,
    query: true,
  },
  "routine:anon.trg_mask_update()": {
    name: "trg_mask_update",
    args: [],
    result: "event_trigger",
    set: false,
    query: false,
  },
  "routine:anon.unload()": { name: "unload", args: [], result: "bool", set: false, query: false },
  "routine:anon.unmask_role(pg_catalog.regrole)": {
    name: "unmask_role",
    args: ["regrole"],
    result: "bool",
    set: false,
    query: false,
  },
  "routine:anon.upper(pg_catalog.text)": { name: "upper", args: ["text"], result: "text", set: false, query: true },
  "routine:anon.version()": { name: "version", args: [], result: "text", set: false, query: true },
} as const;
export type AnonRoutineSpecs = typeof anonRoutineSpecs;
export type AnonMember = keyof AnonRoutineSpecs;

/** Native argument names permit omission without reproducing PostgreSQL defaults. */
export const anonDefaultArgumentNames = {
  "routine:anon.anonymize_database(pg_catalog.text)": ["policy"],
  "routine:anon.detect(pg_catalog.text)": ["dict_lang"],
  "routine:anon.generalize_daterange(pg_catalog.date,pg_catalog.text)": ["val", "step"],
  "routine:anon.generalize_int4range(pg_catalog.int4,pg_catalog.int4)": ["val", "step"],
  "routine:anon.generalize_int8range(pg_catalog.int8,pg_catalog.int8)": ["val", "step"],
  "routine:anon.generalize_numrange(pg_catalog.numeric,pg_catalog.int4)": ["val", "step"],
  "routine:anon.generalize_tsrange(pg_catalog.timestamp,pg_catalog.text)": ["val", "step"],
  "routine:anon.generalize_tstzrange(pg_catalog.timestamptz,pg_catalog.text)": ["val", "step"],
  "routine:anon.hasmask(pg_catalog.regrole,pg_catalog.text)": ["role", "masking_policy"],
  "routine:anon.lorem_ipsum(pg_catalog.int4,pg_catalog.int4,pg_catalog.int4)": ["paragraphs", "words", "characters"],
  "routine:anon.pseudo_city(pg_catalog.anyelement,pg_catalog.text)": ["seed", "salt"],
  "routine:anon.pseudo_company(pg_catalog.anyelement,pg_catalog.text)": ["seed", "salt"],
  "routine:anon.pseudo_country(pg_catalog.anyelement,pg_catalog.text)": ["seed", "salt"],
  "routine:anon.pseudo_email(pg_catalog.anyelement,pg_catalog.text)": ["seed", "salt"],
  "routine:anon.pseudo_first_name(pg_catalog.anyelement,pg_catalog.text)": ["seed", "salt"],
  "routine:anon.pseudo_iban(pg_catalog.anyelement,pg_catalog.text)": ["seed", "salt"],
  "routine:anon.pseudo_last_name(pg_catalog.anyelement,pg_catalog.text)": ["seed", "salt"],
  "routine:anon.pseudo_siret(pg_catalog.anyelement,pg_catalog.text)": ["seed", "salt"],
  "routine:anon.refresh_replica_masking(pg_catalog.text)": ["policy"],
  "routine:anon.set_shift(pg_catalog.int4)": ["val"],
  "routine:anon.start_dynamic_masking(pg_catalog.bool)": ["autoload"],
  "routine:anon.start_replica_masking(pg_catalog.text)": ["policy"],
} as const;
